/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdUtils } from "@ocd/core";
import { OcdDesign } from "@ocd/model";
import { OcdProviderExporter } from "./OcdProviderExporter.js"
import { OutputDataStringArray } from "../OcdExporter.js";
import * as AwsTerraformResources from './provider/aws/resources.js'

interface ResourceMap extends Record<string, string> {}

export class AwsExporter extends OcdProviderExporter {
    terraform: string = ''
    resourceFileMap: ResourceMap = {
        internet_gateway: "aws_networking.tf",
        security_group: "aws_networking.tf",
        subnet: "aws_networking.tf",
        vpc: "aws_networking.tf",

        instance: "aws_compute.tf",

        unknown: "aws_unspecified.tf"
    }
    // Aws Methods
    export = (design: OcdDesign): OutputDataStringArray => {
        // Id to Terraform Resource Name Map
        const idTFResourceMap: Record<string, string> = OcdDesign.getAwsResources(design).reduce((a, c) => {a[c.id] = c.terraformResourceName; return a}, {} as Record<string, string>)
        console.debug('OcdTerraformExporter: awsExport: idTFResourceMap:', idTFResourceMap)
        let outputData: OutputDataStringArray = {}
        const awsModel = design.model.aws
        if (awsModel && Object.keys(idTFResourceMap).length > 0) {
            const uniqueFilenames = [...new Set(Object.values(this.resourceFileMap))]
            outputData = {
                "aws_provider.tf": [this.awsProvider()],
                "aws_provider_variables.tf": [this.awsProviderVariables()],
                "aws_connection.tfvars": [this.awsProviderTFVars()],
                ...uniqueFilenames.toSorted(OcdUtils.simpleSort).reduce((a, c) => {a[c] = [this.autoGeneratedNotice()]; return a}, {} as Record<string, string[]>),
            }
            // Generate Aws Terraform
            Object.entries(awsModel.resources).forEach(([k, v]) => {
                const className = OcdUtils.toClassName('Aws', k)
                const filename = this.resourceFileMap.hasOwnProperty(k) ? this.resourceFileMap[k] : this.resourceFileMap['unknown']
                // @ts-ignore
                v.forEach((r) => {
                    // @ts-ignore
                    const tfResource = new AwsTerraformResources[className](r, idTFResourceMap)
                    if (!outputData.hasOwnProperty(filename)) outputData[filename] = [this.autoGeneratedNotice()]
                    outputData[filename].push(tfResource.generate(r, design))
                })
            })
        }
        return outputData
    }
    awsProvider = () => {return `${this.autoGeneratedNotice()}
terraform {
    required_version = ">= 1.5.0"
    required_providers {
        aws = {
            source  = "hashicorp/aws"
            version = ">= 5.0.0"
        }
    }
}

# ------ Configure the AWS Provider
provider "aws" {
    region     = var.aws_region
    access_key = var.aws_access_key
    secret_key = var.aws_secret_key
}`
    }
    awsProviderVariables = () => {return `${this.autoGeneratedNotice()}
variable "aws_region" {
    type = string
    description = "Name of the AWS Region where the defined resources will be created."
}
variable "aws_access_key" {
    type = string
    description = "AWS Access Key Id used to authenticate API requests."
}
variable "aws_secret_key" {
    type = string
    description = "AWS Secret Access Key used to authenticate API requests."
}
    `}
    awsProviderTFVars = () => {return `${this.autoGeneratedNotice()}
# -- Account Information
aws_region = "Enter your destination AWS Region, e.g. us-east-1"

# -- Credentials (prefer a shared profile / environment variables over inlining secrets)
aws_access_key = "Enter your AWS Access Key Id here"
aws_secret_key = "Enter your AWS Secret Access Key here"
    `}
}
