/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdDesign } from "@ocd/model"
import { OcdProviderExporter } from "./OcdProviderExporter"
import { OutputDataStringArray } from "../OcdExporter"
import { OcdUtils } from "@ocd/core"
import * as GcpTerraformResources  from './provider/gcp/resources'

interface ResourceMap extends Record<string, string> {}

export class GcpExporter extends OcdProviderExporter {
    terraform: string = ''
    resourceFileMap: ResourceMap = {
        google_compute_network: "gcp_networking.tf",

        unknown: "gcp_unspecified.tf"
    }
    // Gcp Methods
    export = (design: OcdDesign): OutputDataStringArray => {
        // Id to Terraform Resource Name Map
        const idTFResourceMap: Record<string, string> = OcdDesign.getGcpResources(design).reduce((a, c) => {a[c.id] = c.terraformResourceName; return a}, {} as Record<string, string>)
        console.debug('OcdTerraformExporter: gcpExport: idTFResourceMap:', idTFResourceMap)
        let outputData: OutputDataStringArray = {}
        if (Object.keys(idTFResourceMap).length > 0) {
            const uniqueFilenames = [...new Set(Object.values(this.resourceFileMap))]
            outputData = {
                "gcp_provider.tf": [this.gcpProvider()],
                // "gcp_provider_variables.tf": [this.gcpProviderVariables()],
                // "gcp_connection.tfvars": [this.gcpProviderTFVars()],
                // "gcp_connection.tfvars": [this.gcpProviderTFVars()],
                // "gcp_metadata.tf": [this.gcpMetadata()],
                ...uniqueFilenames.sort(OcdUtils.simpleSort).reduce((a, c) => {a[c] = [this.autoGeneratedNotice()]; return a}, {} as Record<string, string[]>),
                // "gcp_user_variables.tf": [this.gcpUserVariables(design)],
            }
            // Generate OCI Terraform
            Object.entries(design.model.gcp.resources).forEach(([k, v]) => {
                const className = OcdUtils.toClassName('Gcp', k)
                const filename = this.resourceFileMap.hasOwnProperty(k) ? this.resourceFileMap[k] : this.resourceFileMap['unknown']
                // @ts-ignore
                v.forEach((r: OciResource) => {
                    // @ts-ignore 
                    const tfResource = new GcpTerraformResources[className](r, idTFResourceMap)
                    if (!outputData.hasOwnProperty(filename)) outputData[filename] = [this.autoGeneratedNotice()]
                    outputData[filename].push(tfResource.generate(r, design))
                })
            })
        }
        return outputData
    }
    gcpProvider = () => {return `${this.autoGeneratedNotice()}
terraform {
    required_version = ">= 1.5.0"
}

# ------ Configure the Google GCP Provider
provider "google" {
  project     = var.gcp_project_id
  region      = var.gcp_region
}`
    }
}