#cloud-config
write_files:
  # Add aliases to bash (Note: At time of writing the append flag does not appear to be working)
  - path: /etc/.bashrc
    append: true
    content: |
      alias lh='ls -lash'
      alias lt='ls -last'
      alias env='/usr/bin/env | sort'

runcmd:
  # Install Required Packages because the packages section may not complete before the runcmd
  - sudo bash -c "yum install -y git python-oci-cli oci-utils"
  # Install Required Python Modules
  - sudo bash -c "pip3 install --no-cache-dir flask==1.1.1 gitpython==3.1.11 git-url-parse==1.2.2 gunicorn==20.0.4 oci==2.22.0 oci-cli==2.14.1 openpyxl==3.0.5 pandas==1.1.2 python-magic==0.4.18 pyyaml==5.3.1 requests==2.24.0 xlsxwriter==1.3.6"
  # Clone OKIT
  - sudo bash -c "git clone -b master --depth 1 https://github.com/oracle/oci-designer-toolkit.git /okit"
  - sudo bash -c "mkdir /okit/{log,workspace}"
  # Add additional environment information because append does not appear to work in write_file
  - sudo bash -c "echo 'source /etc/.bashrc' >> /etc/bashrc"
  - sudo bash -c "echo 'export OCI_CLI_AUTH=instance_principal' >> /etc/bashrc"
  - sudo bash -c "echo 'export OKIT_VM_COMPARTMENT=`oci-metadata -g "compartmentID" --value-only`' >> /etc/bashrc"
  # Copy GUnicorn Service File
  - sudo bash -c 'sed "s/{COMPARTMENT_OCID}/`oci-metadata -g compartmentID --value-only`/" /okit/containers/services/gunicorn.service > /etc/systemd/system/gunicorn.service'
  # Enable Gunicorn Service
  - sudo systemctl enable gunicorn.service
  - sudo systemctl start gunicorn.service

final_message: "**** The system is finally up, after $UPTIME seconds ****"
