/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
/*
**
** ======================================================================
** === Auto Generated Code All Edits Will Be Lost During Regeneration ===
** ======================================================================
**
*/

export { OciAnalyticsInstance } from './resources/OciAnalyticsInstance'
export { OciAutonomousDatabase } from './resources/OciAutonomousDatabase'
export { OciBastion } from './resources/OciBastion'
export { OciBucket } from './resources/OciBucket'
export { OciCompartment } from './resources/OciCompartment'
export { OciCpe } from './resources/OciCpe'
export { OciDbSystem } from './resources/OciDbSystem'
export { OciDhcpOptions } from './resources/OciDhcpOptions'
export { OciDrg } from './resources/OciDrg'
export { OciDrgAttachment } from './resources/OciDrgAttachment'
export { OciDrgRouteDistribution } from './resources/OciDrgRouteDistribution'
export { OciDrgRouteDistributionStatement } from './resources/OciDrgRouteDistributionStatement'
export { OciDrgRouteTable } from './resources/OciDrgRouteTable'
export { OciDrgRouteTableRouteRule } from './resources/OciDrgRouteTableRouteRule'
export { OciFileSystem } from './resources/OciFileSystem'
export { OciInstance } from './resources/OciInstance'
export { OciInternetGateway } from './resources/OciInternetGateway'
export { OciIpsec } from './resources/OciIpsec'
export { OciKey } from './resources/OciKey'
export { OciLoadBalancer } from './resources/OciLoadBalancer'
export { OciLocalPeeringGateway } from './resources/OciLocalPeeringGateway'
export { OciMountTarget } from './resources/OciMountTarget'
export { OciMysqlDbSystem } from './resources/OciMysqlDbSystem'
export { OciNatGateway } from './resources/OciNatGateway'
export { OciNetworkLoadBalancer } from './resources/OciNetworkLoadBalancer'
export { OciNetworkSecurityGroup } from './resources/OciNetworkSecurityGroup'
export { OciNetworkSecurityGroupSecurityRule } from './resources/OciNetworkSecurityGroupSecurityRule'
export { OciNosqlIndex } from './resources/OciNosqlIndex'
export { OciNosqlTable } from './resources/OciNosqlTable'
export { OciOkeCluster } from './resources/OciOkeCluster'
export { OciOkeNodePool } from './resources/OciOkeNodePool'
export { OciPolicy } from './resources/OciPolicy'
export { OciRemotePeeringConnection } from './resources/OciRemotePeeringConnection'
export { OciRouteTable } from './resources/OciRouteTable'
export { OciSecret } from './resources/OciSecret'
export { OciSecurityList } from './resources/OciSecurityList'
export { OciServiceGateway } from './resources/OciServiceGateway'
export { OciSubnet } from './resources/OciSubnet'
export { OciVault } from './resources/OciVault'
export { OciVcn } from './resources/OciVcn'
export { OciVnicAttachment } from './resources/OciVnicAttachment'
export { OciVolume } from './resources/OciVolume'
export { OciVolumeAttachment } from './resources/OciVolumeAttachment'

export { OciAnalyticsInstanceConfigs } from './resources/configs/OciAnalyticsInstance'
export { OciAutonomousDatabaseConfigs } from './resources/configs/OciAutonomousDatabase'
export { OciBastionConfigs } from './resources/configs/OciBastion'
export { OciBucketConfigs } from './resources/configs/OciBucket'
export { OciCompartmentConfigs } from './resources/configs/OciCompartment'
export { OciCpeConfigs } from './resources/configs/OciCpe'
export { OciDbSystemConfigs } from './resources/configs/OciDbSystem'
export { OciDhcpOptionsConfigs } from './resources/configs/OciDhcpOptions'
export { OciDrgConfigs } from './resources/configs/OciDrg'
export { OciDrgAttachmentConfigs } from './resources/configs/OciDrgAttachment'
export { OciDrgRouteDistributionConfigs } from './resources/configs/OciDrgRouteDistribution'
export { OciDrgRouteDistributionStatementConfigs } from './resources/configs/OciDrgRouteDistributionStatement'
export { OciDrgRouteTableConfigs } from './resources/configs/OciDrgRouteTable'
export { OciDrgRouteTableRouteRuleConfigs } from './resources/configs/OciDrgRouteTableRouteRule'
export { OciFileSystemConfigs } from './resources/configs/OciFileSystem'
export { OciInstanceConfigs } from './resources/configs/OciInstance'
export { OciInternetGatewayConfigs } from './resources/configs/OciInternetGateway'
export { OciIpsecConfigs } from './resources/configs/OciIpsec'
export { OciKeyConfigs } from './resources/configs/OciKey'
export { OciLoadBalancerConfigs } from './resources/configs/OciLoadBalancer'
export { OciLocalPeeringGatewayConfigs } from './resources/configs/OciLocalPeeringGateway'
export { OciMountTargetConfigs } from './resources/configs/OciMountTarget'
export { OciMysqlDbSystemConfigs } from './resources/configs/OciMysqlDbSystem'
export { OciNatGatewayConfigs } from './resources/configs/OciNatGateway'
export { OciNetworkLoadBalancerConfigs } from './resources/configs/OciNetworkLoadBalancer'
export { OciNetworkSecurityGroupConfigs } from './resources/configs/OciNetworkSecurityGroup'
export { OciNetworkSecurityGroupSecurityRuleConfigs } from './resources/configs/OciNetworkSecurityGroupSecurityRule'
export { OciNosqlIndexConfigs } from './resources/configs/OciNosqlIndex'
export { OciNosqlTableConfigs } from './resources/configs/OciNosqlTable'
export { OciOkeClusterConfigs } from './resources/configs/OciOkeCluster'
export { OciOkeNodePoolConfigs } from './resources/configs/OciOkeNodePool'
export { OciPolicyConfigs } from './resources/configs/OciPolicy'
export { OciRemotePeeringConnectionConfigs } from './resources/configs/OciRemotePeeringConnection'
export { OciRouteTableConfigs } from './resources/configs/OciRouteTable'
export { OciSecretConfigs } from './resources/configs/OciSecret'
export { OciSecurityListConfigs } from './resources/configs/OciSecurityList'
export { OciServiceGatewayConfigs } from './resources/configs/OciServiceGateway'
export { OciSubnetConfigs } from './resources/configs/OciSubnet'
export { OciVaultConfigs } from './resources/configs/OciVault'
export { OciVcnConfigs } from './resources/configs/OciVcn'
export { OciVnicAttachmentConfigs } from './resources/configs/OciVnicAttachment'
export { OciVolumeConfigs } from './resources/configs/OciVolume'
export { OciVolumeAttachmentConfigs } from './resources/configs/OciVolumeAttachment'
    