/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
    
    import * as AutoGenerated from "./generated/OciBootVolumeAttachment"
    
    export class OciBootVolumeAttachment extends AutoGenerated.OciBootVolumeAttachment {}
    
    export default OciBootVolumeAttachment
    