/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
    
    import * as AutoGenerated from "./generated/OciCpe"
    
    export class OciCpe extends AutoGenerated.OciCpe {}
    
    export default OciCpe
    