/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
    
    import * as AutoGenerated from "./generated/OciNetworkFirewallPolicy.js"
    
    export class OciNetworkFirewallPolicy extends AutoGenerated.OciNetworkFirewallPolicy {}
    
    export default OciNetworkFirewallPolicy
    