OCI_HOME_REGION="<home_region>"
OCI_TENANT="<tenant_name>"
IDCS_CLIENT_ID="<client_id>"
IDCS_CLIENT_SECRET="<client_secret>"
IDCS_API_BASE_URL="https://idcs-<idcs_instance_id>.identity.oraclecloud.com"
OKIT_SERVER_BASE="<server_base_url>"
