/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciDrgRouteTableRouteRule"

export interface OciDrgRouteTableRouteRule extends AutoGenerated.OciDrgRouteTableRouteRule {}

export namespace OciDrgRouteTableRouteRule {
    export function newResource(type?: string): OciDrgRouteTableRouteRule {
        return {
            ...AutoGenerated.OciDrgRouteTableRouteRule.newResource('drg_route_table_route_rule'),
        }
    }
    
}

export class OciDrgRouteTableRouteRuleClient {
    static new(): OciDrgRouteTableRouteRule {
        return OciDrgRouteTableRouteRule.newResource()
    }
}

export default OciDrgRouteTableRouteRuleClient
