/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign"
import * as AutoGenerated from "./generated/AzureSqlDatabase"

export interface AzureSqlDatabase extends AutoGenerated.AzureSqlDatabase {}

export namespace AzureSqlDatabase {
    
    export function newResource(type?: string): AzureSqlDatabase {
        const resource = {
            ...AutoGenerated.AzureSqlDatabase.newResource('sql_database'),
        }
        return resource
    }
    export function cloneResource(resource: AzureSqlDatabase, type?: string): AzureSqlDatabase {
        return AutoGenerated.AzureSqlDatabase.cloneResource(resource, 'sql_database') as AzureSqlDatabase
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: AzureSqlDatabase): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: AzureSqlDatabase, parentId: string): AzureSqlDatabase {
        return resource
    }
    export function getConnectionIds(resource: AzureSqlDatabase, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class AzureSqlDatabaseClient extends AutoGenerated.AzureSqlDatabaseClient {
    static new(): AzureSqlDatabase {
        return AzureSqlDatabase.newResource()
    }
    static clone(resource: AzureSqlDatabase): AzureSqlDatabase {
        return AzureSqlDatabase.cloneResource(resource)
    }
}

export default AzureSqlDatabaseClient
