/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciCompartment.js"
import { OciModelResources as Model } from '@ocd/model'

export class OciCompartment extends AutoGenerated.OciCompartment {
    constructor(resource: Model.OciCompartment, idTFResourceMap: Record<string, string> = {}, isHomeRegion: boolean = true) {
        super(resource, idTFResourceMap, isHomeRegion)
    }
}

export default OciCompartment
