/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciCpe"

export class OciCpe extends AutoGenerated.OciCpe {
    retrieveCpeDeviceShapeId = (): string => {
        const content =`
data "oci_core_cpe_device_shapes" "${this.terraformResourceName}CpeDeviceShapes" {
    filter {
        name = "cpe_device_info.platform_software_version"
        values = ["${this.resource.cpeDeviceShapeId}"]
    }
}
locals {
    ${this.terraformResourceName}_cpeDeviceShape_id = data.oci_core_cpe_device_shapes.${this.terraformResourceName}CpeDeviceShapes.cpe_device_shapes[0]["cpe_device_shape_id"]
}
`
        return content
    }
}

export default OciCpe
