/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciDhcpOptions.js"
import { OciModelResources as Model, OcdDesign } from '@ocd/model'

export class OciDhcpOptions extends AutoGenerated.OciDhcpOptions {
    /*
    ** Override Generate Terraform Resource / Data Statement(s) to check for Default
    */
    generate(resource: Model.OciDhcpOptions, design: OcdDesign) {
        resource = resource ? resource : this.resource
        if (resource.locked) {
            return this.generateData(resource)
        } else if (resource.vcnDefault) {
            return this.generateDefaultResource(resource, design)
        } else {
            return this.generateResource(resource, design)
        }
    }

    generateDefaultResource(resource: Model.OciDhcpOptions, design: OcdDesign) {
        const content = `
# ------ Update Default Dhcp Options
resource "oci_core_default_dhcp_options" "${resource.terraformResourceName}" {
    ${this.manageDefaultResourceId(resource)}
    ${this.displayName(resource)}
    ${this.domainNameType(resource, resource)}
    ${this.optionsObjectList(resource.options, resource)}
    ${this.tags(resource, design)}
}

locals {
    ${resource.terraformResourceName}_id = oci_core_default_dhcp_options.${resource.terraformResourceName}.id
    ${this.generateAdditionalResourceLocals(resource)}
}
`
    return content
    }
    // Simple Elements
    manageDefaultResourceId = (resource: Record<string, any>, level=0): string => {return `${this.indentation[level]}manage_default_resource_id = local.${this.idTFResourceMap[resource.vcnId]}_default_dhcp_options_id`}
}

export default OciDhcpOptions
