/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciInstance.js"
import { OciModelResources as Model, OciResource } from '@ocd/model'

interface PluginConfig {
    name?: string
    desiredState?: string
}

export class OciInstance extends AutoGenerated.OciInstance {

    // Metadata / Cache - Dropdown Data Generation
    retrieveImageId = () => {
        const content = `
data "oci_core_images" "${this.terraformResourceName}Images" {
    ${this.compartmentId(this.resource)}
    filter {
       name =  "operating_system"
       values = ["${this.resource.sourceDetails?.sourceId?.split('-')[0]}"]
    }
    filter {
       name =  "operating_system_version"
       values = ["${this.resource.sourceDetails?.sourceId?.split('-')[1]}"]
    }
}

locals {
    ${this.terraformResourceName}_image_id = length(data.oci_core_images.${this.terraformResourceName}Images.images) == 0 ? "" : data.oci_core_images.${this.terraformResourceName}Images.images[0]["id"]
}
`
    return content
    }
    // Additional Locals
    generateAdditionalResourceLocals(resource: OciResource) {
        return `${resource.terraformResourceName}_private_ip = oci_core_instance.${resource.terraformResourceName}.private_ip
    ${resource.terraformResourceName}_public_ip = oci_core_instance.${resource.terraformResourceName}.public_ip
        `
    }
    // Overrides
    // User Data (userData)
    metadataUserData = (resource: Record<string, any>, rootResource: OciResource, level=0): string => {return this.isAssignMetadataUserData(resource, rootResource) ? this.generateBase64EncodedTextAttribute("user_data", resource.userData, false, level) : ''}
    isAssignMetadataUserData = (resource: Record<string, any>, rootResource: OciResource): boolean => {return this.isPropertyAssignConditionTrue(false, {}, resource, rootResource) ? this.isGenerateAttribute("user_data", resource.userData, false) : false}

    // Issue #563: render the agent_config.plugins_config list (Oracle Cloud Agent plugins such as
    // Bastion, Vulnerability Scanning, Management Agent, ...). The generated agentConfigObject only
    // emits a placeholder comment for the list, so override it to render the plugins_config blocks and
    // to emit the agent_config block when plugins are defined (not only when the legacy booleans are set).
    agentConfigObject = (resource: Model.OciInstance.AgentConfig.AgentConfig | undefined, rootResource: OciResource, level=0): string => {
        return resource && this.isAssignAgentConfigObject(resource, rootResource) ? `${this.indentation[level]}agent_config {
    ${this.agentConfigAreAllPluginsDisabled(resource, rootResource, level+1)}
    ${this.agentConfigIsManagementDisabled(resource, rootResource, level+1)}
    ${this.agentConfigIsMonitoringDisabled(resource, rootResource, level+1)}
${this.pluginsConfigObjectList(resource.pluginsConfig as PluginConfig[] | undefined, level+1)}
    ${this.indentation[level]}}` : '# agent_config is not defined. Type: object SubType:  Required: false'
    }
    isAssignAgentConfigObject = (resource: Model.OciInstance.AgentConfig.AgentConfig | undefined, rootResource: OciResource): boolean => {
        return resource !== undefined && this.isPropertyAssignConditionTrue(false, {}, resource, rootResource) && (this.isAssignAgentConfigAreAllPluginsDisabled(resource, rootResource) || this.isAssignAgentConfigIsManagementDisabled(resource, rootResource) || this.isAssignAgentConfigIsMonitoringDisabled(resource, rootResource) || this.hasValidPluginsConfig(resource.pluginsConfig as PluginConfig[] | undefined))
    }

    hasValidPluginsConfig(plugins: PluginConfig[] | undefined): boolean {
        return !!plugins && plugins.filter((plugin) => plugin.name && plugin.desiredState).length > 0
    }

    pluginsConfigObjectList(plugins: PluginConfig[] | undefined, level=0): string {
        const validPlugins = plugins ? plugins.filter((plugin) => plugin.name && plugin.desiredState) : []
        if (validPlugins.length === 0) return `${this.indentation[level]}# plugins_config is not defined. Type: list SubType: object Required: false`
        return validPlugins
            .map((plugin) => `${this.indentation[level]}plugins_config {
${this.generateTextAttribute('name', plugin.name, true, level+1)}
${this.generateTextAttribute('desired_state', plugin.desiredState, true, level+1)}
${this.indentation[level]}}`)
            .join('\n')
    }
}

export default OciInstance
