/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdDesign, OciResource } from "@ocd/model"
import * as AutoGenerated from "./generated/OciLoadBalancerListener.js"

export class OciLoadBalancerListener extends AutoGenerated.OciLoadBalancerListener {
    compartmentId = (resource: Record<string, any>, level=0): string => ''
    tags = (resource: OciResource, design: OcdDesign): string => ''
}

export default OciLoadBalancerListener
