/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciRouteTable.js"
import { OciModelResources as Model, OcdDesign } from '@ocd/model'

export class OciRouteTable extends AutoGenerated.OciRouteTable {
    /*
    ** Override Generate Terraform Resource / Data Statement(s) to check for Default
    */
    generate(resource: Model.OciRouteTable, design: OcdDesign) {
        resource = resource ? resource : this.resource
        if (resource.locked) {
            return this.generateData(resource)
        } else if (resource.vcnDefault) {
            return this.generateDefaultResource(resource, design)
        } else {
            return this.generateResource(resource, design)
        }
    }

    generateDefaultResource(resource: Model.OciRouteTable, design: OcdDesign) {
        const content = `
# ------ Update Default Route Table
resource "oci_core_default_route_table" "${resource.terraformResourceName}" {
    ${this.manageDefaultResourceId(resource)}
    ${this.displayName(resource)}
    ${this.routeRulesObjectList(resource.routeRules, resource)}
    ${this.tags(resource, design)}
}

locals {
    ${resource.terraformResourceName}_id = oci_core_default_route_table.${resource.terraformResourceName}.id
    ${this.generateAdditionalResourceLocals(resource)}
}
`
    return content
    }
    // Simple Elements
    manageDefaultResourceId = (resource: Record<string, any>, level=0): string => {return `${this.indentation[level]}manage_default_resource_id = local.${this.idTFResourceMap[resource.vcnId]}_default_route_table_id`}
}

export default OciRouteTable
