/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciDhcpOptionsModel"

export interface OciDhcpOptionsModel extends AutoGenerated.OciDhcpOptionsAutoGeneratedModel {}

export interface OciOptionsModel extends AutoGenerated.OciOptionsModel{}

export namespace OciDhcpOptionsModel {
    export function newResource(type?: string): OciDhcpOptionsModel {
        return {
            ...AutoGenerated.OciDhcpOptionsAutoGeneratedModel.newResource('dhcp_options'),
        }
    }
    
    export function newOciOptionsModel(): OciOptionsModel {
        return {
            ...AutoGenerated.OciDhcpOptionsAutoGeneratedModel.newOciOptionsModel(),
        }
    }

}

export class OciDhcpOptionsModelClient {
    static new(): OciDhcpOptionsModel {
        return OciDhcpOptionsModel.newResource()
    }
}

export default OciDhcpOptionsModelClient
