/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciDrgRouteDistributionStatementModel"

export interface OciDrgRouteDistributionStatementModel extends AutoGenerated.OciDrgRouteDistributionStatementAutoGeneratedModel {}

export interface OciMatchCriteriaModel extends AutoGenerated.OciMatchCriteriaModel{}

export namespace OciDrgRouteDistributionStatementModel {
    export function newResource(type?: string): OciDrgRouteDistributionStatementModel {
        return {
            ...AutoGenerated.OciDrgRouteDistributionStatementAutoGeneratedModel.newResource('drg_route_distribution_statement'),
        }
    }
    
    export function newOciMatchCriteriaModel(): OciMatchCriteriaModel {
        return {
            ...AutoGenerated.OciDrgRouteDistributionStatementAutoGeneratedModel.newOciMatchCriteriaModel(),
        }
    }

}

export class OciDrgRouteDistributionStatementModelClient {
    static new(): OciDrgRouteDistributionStatementModel {
        return OciDrgRouteDistributionStatementModel.newResource()
    }
}

export default OciDrgRouteDistributionStatementModelClient
