/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OciDrgAutoGenerated } from "./generated/OciDrg"

export interface OciDrg extends OciDrgAutoGenerated {
}

export namespace OciDrg {
    export function newResource(type?: string): OciDrg {
        return {
            ...OciDrgAutoGenerated.newResource('drg'),
        }
    }
}

export class OciDrgClient {
    static new(): OciDrg {
        return OciDrg.newResource()
    }
}

export default OciDrgClient
