/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OciDhcpOptionsAutoGeneratedModel } from "./generated/OciDhcpOptionsModel"

export interface OciDhcpOptionsModel extends OciDhcpOptionsAutoGeneratedModel {
}

export namespace OciDhcpOptionsModel {
    export function newResource(type?: string): OciDhcpOptionsModel {
        return {
            ...OciDhcpOptionsAutoGeneratedModel.newResource('dhcp_options'),
        }
    }
}

export class OciDhcpOptionsModelClient {
    static new(): OciDhcpOptionsModel {
        return OciDhcpOptionsModel.newResource()
    }
}

export default OciDhcpOptionsModelClient
