/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OciInternetGatewayAutoGeneratedModel } from "./generated/OciInternetGatewayModel"

export interface OciInternetGatewayModel extends OciInternetGatewayAutoGeneratedModel {
}

export namespace OciInternetGatewayModel {
    export function newResource(type?: string): OciInternetGatewayModel {
        return {
            ...OciInternetGatewayAutoGeneratedModel.newResource('internet_gateway'),
        }
    }
}

export class OciInternetGatewayModelClient {
    static new(): OciInternetGatewayModel {
        return OciInternetGatewayModel.newResource()
    }
}

export default OciInternetGatewayModelClient
