/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciNatGatewayModel"

export interface OciNatGatewayModel extends AutoGenerated.OciNatGatewayModel {}

export namespace OciNatGatewayModel {
    export function newResource(type?: string): OciNatGatewayModel {
        return {
            ...AutoGenerated.OciNatGatewayModel.newResource('nat_gateway'),
        }
    }
    
}

export class OciNatGatewayModelClient {
    static new(): OciNatGatewayModel {
        return OciNatGatewayModel.newResource()
    }
}

export default OciNatGatewayModelClient
