/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciNetworkSecurityGroupModel"

export interface OciNetworkSecurityGroupModel extends AutoGenerated.OciNetworkSecurityGroupAutoGeneratedModel {}

export namespace OciNetworkSecurityGroupModel {
    export function newResource(type?: string): OciNetworkSecurityGroupModel {
        return {
            ...AutoGenerated.OciNetworkSecurityGroupAutoGeneratedModel.newResource('network_security_group'),
        }
    }
    
}

export class OciNetworkSecurityGroupModelClient {
    static new(): OciNetworkSecurityGroupModel {
        return OciNetworkSecurityGroupModel.newResource()
    }
}

export default OciNetworkSecurityGroupModelClient
