/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OciServiceGatewayAutoGeneratedModel } from "./generated/OciServiceGatewayModel"

export interface OciServiceGatewayModel extends OciServiceGatewayAutoGeneratedModel {
}

export namespace OciServiceGatewayModel {
    export function newResource(type?: string): OciServiceGatewayModel {
        return {
            ...OciServiceGatewayAutoGeneratedModel.newResource('service_gateway'),
        }
    }
}

export class OciServiceGatewayModelClient {
    static new(): OciServiceGatewayModel {
        return OciServiceGatewayModel.newResource()
    }
}

export default OciServiceGatewayModelClient
