/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OciSubnetAutoGeneratedModel } from "./generated/OciSubnetModel"

export interface OciSubnetModel extends OciSubnetAutoGeneratedModel {
}

export namespace OciSubnetModel {
    export function newResource(type?: string): OciSubnetModel {
        return {
            ...OciSubnetAutoGeneratedModel.newResource('subnet'),
        }
    }
}

export class OciSubnetModelClient {
    static new(): OciSubnetModel {
        return OciSubnetModel.newResource()
    }
}

export default OciSubnetModelClient
