/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OciVolumeAutoGeneratedModel } from "./generated/OciVolumeModel"

export interface OciVolumeModel extends OciVolumeAutoGeneratedModel {
}

export namespace OciVolumeModel {
    export function newResource(type?: string): OciVolumeModel {
        return {
            ...OciVolumeAutoGeneratedModel.newResource('volume'),
        }
    }
}

export class OciVolumeModelClient {
    static new(): OciVolumeModel {
        return OciVolumeModel.newResource()
    }
}

export default OciVolumeModelClient
