/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OciVcnAutoGeneratedModel } from "./generated/OciVcnModel"

export interface OciVcnModel extends OciVcnAutoGeneratedModel {
}

export namespace OciVcnModel {
    export function newResource(type?: string): OciVcnModel {
        return {
            ...OciVcnAutoGeneratedModel.newResource('vcn'),
        }
    }
}

export class OciVcnModelClient {
    static new(): OciVcnModel {
        return OciVcnModel.newResource()
    }
}

export default OciVcnModelClient
