/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciApmSyntheticsMonitor.js"

export interface OciApmSyntheticsMonitor extends AutoGenerated.OciApmSyntheticsMonitor {}

export namespace OciApmSyntheticsMonitor {
    export namespace Configuration {
        export interface Configuration extends AutoGenerated.OciApmSyntheticsMonitor.Configuration.Configuration {}
        export function newConfiguration(): Configuration {return AutoGenerated.OciApmSyntheticsMonitor.Configuration.newConfiguration()}
        
    }
    export namespace VantagePoints {
        export interface VantagePoints extends AutoGenerated.OciApmSyntheticsMonitor.VantagePoints.VantagePoints {}
        export function newVantagePoints(): VantagePoints {return AutoGenerated.OciApmSyntheticsMonitor.VantagePoints.newVantagePoints()}
        
    }
    export function newResource(type?: string): OciApmSyntheticsMonitor {
        const resource = {
            ...AutoGenerated.OciApmSyntheticsMonitor.newResource('apm_synthetics_monitor'),
        }
        return resource
    }
    export function cloneResource(resource: OciApmSyntheticsMonitor, type?: string): OciApmSyntheticsMonitor {
        return AutoGenerated.OciApmSyntheticsMonitor.cloneResource(resource, 'apm_synthetics_monitor') as OciApmSyntheticsMonitor
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciApmSyntheticsMonitor): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciApmSyntheticsMonitor, parentId: string): OciApmSyntheticsMonitor {
        return resource
    }
    export function getConnectionIds(resource: OciApmSyntheticsMonitor, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciApmSyntheticsMonitorClient extends AutoGenerated.OciApmSyntheticsMonitorClient {
    static new(): OciApmSyntheticsMonitor {
        return OciApmSyntheticsMonitor.newResource()
    }
    static clone(resource: OciApmSyntheticsMonitor): OciApmSyntheticsMonitor {
        return OciApmSyntheticsMonitor.cloneResource(resource)
    }
}

export default OciApmSyntheticsMonitorClient
