/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciAutonomousVmCluster.js"

export interface OciAutonomousVmCluster extends AutoGenerated.OciAutonomousVmCluster {}

export namespace OciAutonomousVmCluster {
    
    export function newResource(type?: string): OciAutonomousVmCluster {
        const resource = {
            ...AutoGenerated.OciAutonomousVmCluster.newResource('autonomous_vm_cluster'),
        }
        return resource
    }
    export function cloneResource(resource: OciAutonomousVmCluster, type?: string): OciAutonomousVmCluster {
        return AutoGenerated.OciAutonomousVmCluster.cloneResource(resource, 'autonomous_vm_cluster') as OciAutonomousVmCluster
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciAutonomousVmCluster): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciAutonomousVmCluster, parentId: string): OciAutonomousVmCluster {
        return resource
    }
    export function getConnectionIds(resource: OciAutonomousVmCluster, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciAutonomousVmClusterClient extends AutoGenerated.OciAutonomousVmClusterClient {
    static new(): OciAutonomousVmCluster {
        return OciAutonomousVmCluster.newResource()
    }
    static clone(resource: OciAutonomousVmCluster): OciAutonomousVmCluster {
        return OciAutonomousVmCluster.cloneResource(resource)
    }
}

export default OciAutonomousVmClusterClient
