/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciArtifactsContainerRepository.js"

export interface OciArtifactsContainerRepository extends AutoGenerated.OciArtifactsContainerRepository {}

export namespace OciArtifactsContainerRepository {
    
    export function newResource(type?: string): OciArtifactsContainerRepository {
        const resource = {
            ...AutoGenerated.OciArtifactsContainerRepository.newResource('artifacts_container_repository'),
        }
        return resource
    }
    export function cloneResource(resource: OciArtifactsContainerRepository, type?: string): OciArtifactsContainerRepository {
        return AutoGenerated.OciArtifactsContainerRepository.cloneResource(resource, 'artifacts_container_repository') as OciArtifactsContainerRepository
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciArtifactsContainerRepository): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciArtifactsContainerRepository, parentId: string): OciArtifactsContainerRepository {
        return resource
    }
    export function getConnectionIds(resource: OciArtifactsContainerRepository, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciArtifactsContainerRepositoryClient extends AutoGenerated.OciArtifactsContainerRepositoryClient {
    static new(): OciArtifactsContainerRepository {
        return OciArtifactsContainerRepository.newResource()
    }
    static clone(resource: OciArtifactsContainerRepository): OciArtifactsContainerRepository {
        return OciArtifactsContainerRepository.cloneResource(resource)
    }
}

export default OciArtifactsContainerRepositoryClient
