/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciBastionSession.js"

export interface OciBastionSession extends AutoGenerated.OciBastionSession {}

export namespace OciBastionSession {
    export namespace KeyDetails {
        export interface KeyDetails extends AutoGenerated.OciBastionSession.KeyDetails.KeyDetails {}
        export function newKeyDetails(): KeyDetails {return AutoGenerated.OciBastionSession.KeyDetails.newKeyDetails()}
        
    }
    export namespace TargetResourceDetails {
        export interface TargetResourceDetails extends AutoGenerated.OciBastionSession.TargetResourceDetails.TargetResourceDetails {}
        export function newTargetResourceDetails(): TargetResourceDetails {return AutoGenerated.OciBastionSession.TargetResourceDetails.newTargetResourceDetails()}
        
    }
    export function newResource(type?: string): OciBastionSession {
        const resource = {
            ...AutoGenerated.OciBastionSession.newResource('bastion_session'),
        }
        return resource
    }
    export function cloneResource(resource: OciBastionSession, type?: string): OciBastionSession {
        return AutoGenerated.OciBastionSession.cloneResource(resource, 'bastion_session') as OciBastionSession
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciBastionSession): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciBastionSession, parentId: string): OciBastionSession {
        return resource
    }
    export function getConnectionIds(resource: OciBastionSession, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciBastionSessionClient extends AutoGenerated.OciBastionSessionClient {
    static new(): OciBastionSession {
        return OciBastionSession.newResource()
    }
    static clone(resource: OciBastionSession): OciBastionSession {
        return OciBastionSession.cloneResource(resource)
    }
}

export default OciBastionSessionClient
