/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciBudget.js"

export interface OciBudget extends AutoGenerated.OciBudget {}

export namespace OciBudget {
    
    export function newResource(type?: string): OciBudget {
        const resource = {
            ...AutoGenerated.OciBudget.newResource('budget'),
        }
        return resource
    }
    export function cloneResource(resource: OciBudget, type?: string): OciBudget {
        return AutoGenerated.OciBudget.cloneResource(resource, 'budget') as OciBudget
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciBudget): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciBudget, parentId: string): OciBudget {
        return resource
    }
    export function getConnectionIds(resource: OciBudget, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciBudgetClient extends AutoGenerated.OciBudgetClient {
    static new(): OciBudget {
        return OciBudget.newResource()
    }
    static clone(resource: OciBudget): OciBudget {
        return OciBudget.cloneResource(resource)
    }
}

export default OciBudgetClient
