/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciBdsInstance.js"

export interface OciBdsInstance extends AutoGenerated.OciBdsInstance {}

export namespace OciBdsInstance {
    export namespace MasterNode {
        export interface MasterNode extends AutoGenerated.OciBdsInstance.MasterNode.MasterNode {}
        export function newMasterNode(): MasterNode {return AutoGenerated.OciBdsInstance.MasterNode.newMasterNode()}
        
    }
    export namespace UtilNode {
        export interface UtilNode extends AutoGenerated.OciBdsInstance.UtilNode.UtilNode {}
        export function newUtilNode(): UtilNode {return AutoGenerated.OciBdsInstance.UtilNode.newUtilNode()}
        
    }
    export namespace WorkerNode {
        export interface WorkerNode extends AutoGenerated.OciBdsInstance.WorkerNode.WorkerNode {}
        export function newWorkerNode(): WorkerNode {return AutoGenerated.OciBdsInstance.WorkerNode.newWorkerNode()}
        
    }
    export function newResource(type?: string): OciBdsInstance {
        const resource = {
            ...AutoGenerated.OciBdsInstance.newResource('bds_instance'),
        }
        return resource
    }
    export function cloneResource(resource: OciBdsInstance, type?: string): OciBdsInstance {
        return AutoGenerated.OciBdsInstance.cloneResource(resource, 'bds_instance') as OciBdsInstance
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciBdsInstance): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciBdsInstance, parentId: string): OciBdsInstance {
        return resource
    }
    export function getConnectionIds(resource: OciBdsInstance, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciBdsInstanceClient extends AutoGenerated.OciBdsInstanceClient {
    static new(): OciBdsInstance {
        return OciBdsInstance.newResource()
    }
    static clone(resource: OciBdsInstance): OciBdsInstance {
        return OciBdsInstance.cloneResource(resource)
    }
}

export default OciBdsInstanceClient
