/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciCloudBridgeAgentDependency.js"

export interface OciCloudBridgeAgentDependency extends AutoGenerated.OciCloudBridgeAgentDependency {}

export namespace OciCloudBridgeAgentDependency {

    export function newResource(type?: string): OciCloudBridgeAgentDependency {
        const resource = {
            ...AutoGenerated.OciCloudBridgeAgentDependency.newResource('cloud_bridge_agent_dependency'),
        }
        return resource
    }
    export function cloneResource(resource: OciCloudBridgeAgentDependency, type?: string): OciCloudBridgeAgentDependency {
        return AutoGenerated.OciCloudBridgeAgentDependency.cloneResource(resource, 'cloud_bridge_agent_dependency') as OciCloudBridgeAgentDependency
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciCloudBridgeAgentDependency): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciCloudBridgeAgentDependency, parentId: string): OciCloudBridgeAgentDependency {
        return resource
    }
    export function getConnectionIds(resource: OciCloudBridgeAgentDependency, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciCloudBridgeAgentDependencyClient extends AutoGenerated.OciCloudBridgeAgentDependencyClient {
    static new(): OciCloudBridgeAgentDependency {
        return OciCloudBridgeAgentDependency.newResource()
    }
    static clone(resource: OciCloudBridgeAgentDependency): OciCloudBridgeAgentDependency {
        return OciCloudBridgeAgentDependency.cloneResource(resource)
    }
}

export default OciCloudBridgeAgentDependencyClient
