/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciCertificatesCaBundle.js"

export interface OciCertificatesCaBundle extends AutoGenerated.OciCertificatesCaBundle {}

export namespace OciCertificatesCaBundle {
    
    export function newResource(type?: string): OciCertificatesCaBundle {
        const resource = {
            ...AutoGenerated.OciCertificatesCaBundle.newResource('certificates_ca_bundle'),
        }
        return resource
    }
    export function cloneResource(resource: OciCertificatesCaBundle, type?: string): OciCertificatesCaBundle {
        return AutoGenerated.OciCertificatesCaBundle.cloneResource(resource, 'certificates_ca_bundle') as OciCertificatesCaBundle
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciCertificatesCaBundle): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciCertificatesCaBundle, parentId: string): OciCertificatesCaBundle {
        return resource
    }
    export function getConnectionIds(resource: OciCertificatesCaBundle, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciCertificatesCaBundleClient extends AutoGenerated.OciCertificatesCaBundleClient {
    static new(): OciCertificatesCaBundle {
        return OciCertificatesCaBundle.newResource()
    }
    static clone(resource: OciCertificatesCaBundle): OciCertificatesCaBundle {
        return OciCertificatesCaBundle.cloneResource(resource)
    }
}

export default OciCertificatesCaBundleClient
