/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciComputeCluster.js"

export interface OciComputeCluster extends AutoGenerated.OciComputeCluster {}

export namespace OciComputeCluster {
    
    export function newResource(type?: string): OciComputeCluster {
        const resource = {
            ...AutoGenerated.OciComputeCluster.newResource('compute_cluster'),
        }
        return resource
    }
    export function cloneResource(resource: OciComputeCluster, type?: string): OciComputeCluster {
        return AutoGenerated.OciComputeCluster.cloneResource(resource, 'compute_cluster') as OciComputeCluster
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciComputeCluster): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciComputeCluster, parentId: string): OciComputeCluster {
        return resource
    }
    export function getConnectionIds(resource: OciComputeCluster, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciComputeClusterClient extends AutoGenerated.OciComputeClusterClient {
    static new(): OciComputeCluster {
        return OciComputeCluster.newResource()
    }
    static clone(resource: OciComputeCluster): OciComputeCluster {
        return OciComputeCluster.cloneResource(resource)
    }
}

export default OciComputeClusterClient
