/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciCloudBridgeDiscoverySchedule.js"

export interface OciCloudBridgeDiscoverySchedule extends AutoGenerated.OciCloudBridgeDiscoverySchedule {}

export namespace OciCloudBridgeDiscoverySchedule {

    export function newResource(type?: string): OciCloudBridgeDiscoverySchedule {
        const resource = {
            ...AutoGenerated.OciCloudBridgeDiscoverySchedule.newResource('cloud_bridge_discovery_schedule'),
        }
        return resource
    }
    export function cloneResource(resource: OciCloudBridgeDiscoverySchedule, type?: string): OciCloudBridgeDiscoverySchedule {
        return AutoGenerated.OciCloudBridgeDiscoverySchedule.cloneResource(resource, 'cloud_bridge_discovery_schedule') as OciCloudBridgeDiscoverySchedule
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciCloudBridgeDiscoverySchedule): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciCloudBridgeDiscoverySchedule, parentId: string): OciCloudBridgeDiscoverySchedule {
        return resource
    }
    export function getConnectionIds(resource: OciCloudBridgeDiscoverySchedule, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciCloudBridgeDiscoveryScheduleClient extends AutoGenerated.OciCloudBridgeDiscoveryScheduleClient {
    static new(): OciCloudBridgeDiscoverySchedule {
        return OciCloudBridgeDiscoverySchedule.newResource()
    }
    static clone(resource: OciCloudBridgeDiscoverySchedule): OciCloudBridgeDiscoverySchedule {
        return OciCloudBridgeDiscoverySchedule.cloneResource(resource)
    }
}

export default OciCloudBridgeDiscoveryScheduleClient
