/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciCloudMigrationsMigrationAsset.js"

export interface OciCloudMigrationsMigrationAsset extends AutoGenerated.OciCloudMigrationsMigrationAsset {}

export namespace OciCloudMigrationsMigrationAsset {

    export function newResource(type?: string): OciCloudMigrationsMigrationAsset {
        const resource = {
            ...AutoGenerated.OciCloudMigrationsMigrationAsset.newResource('cloud_migrations_migration_asset'),
        }
        return resource
    }
    export function cloneResource(resource: OciCloudMigrationsMigrationAsset, type?: string): OciCloudMigrationsMigrationAsset {
        return AutoGenerated.OciCloudMigrationsMigrationAsset.cloneResource(resource, 'cloud_migrations_migration_asset') as OciCloudMigrationsMigrationAsset
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciCloudMigrationsMigrationAsset): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciCloudMigrationsMigrationAsset, parentId: string): OciCloudMigrationsMigrationAsset {
        return resource
    }
    export function getConnectionIds(resource: OciCloudMigrationsMigrationAsset, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciCloudMigrationsMigrationAssetClient extends AutoGenerated.OciCloudMigrationsMigrationAssetClient {
    static new(): OciCloudMigrationsMigrationAsset {
        return OciCloudMigrationsMigrationAsset.newResource()
    }
    static clone(resource: OciCloudMigrationsMigrationAsset): OciCloudMigrationsMigrationAsset {
        return OciCloudMigrationsMigrationAsset.cloneResource(resource)
    }
}

export default OciCloudMigrationsMigrationAssetClient
