/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciCloudGuardTarget.js"

export interface OciCloudGuardTarget extends AutoGenerated.OciCloudGuardTarget {}

export namespace OciCloudGuardTarget {
    export namespace TargetDetectorRecipes {
        export interface TargetDetectorRecipes extends AutoGenerated.OciCloudGuardTarget.TargetDetectorRecipes.TargetDetectorRecipes {}
        export function newTargetDetectorRecipes(): TargetDetectorRecipes {return AutoGenerated.OciCloudGuardTarget.TargetDetectorRecipes.newTargetDetectorRecipes()}
        
    }
    export namespace TargetResponderRecipes {
        export interface TargetResponderRecipes extends AutoGenerated.OciCloudGuardTarget.TargetResponderRecipes.TargetResponderRecipes {}
        export function newTargetResponderRecipes(): TargetResponderRecipes {return AutoGenerated.OciCloudGuardTarget.TargetResponderRecipes.newTargetResponderRecipes()}
        
    }
    export function newResource(type?: string): OciCloudGuardTarget {
        const resource = {
            ...AutoGenerated.OciCloudGuardTarget.newResource('cloud_guard_target'),
        }
        return resource
    }
    export function cloneResource(resource: OciCloudGuardTarget, type?: string): OciCloudGuardTarget {
        return AutoGenerated.OciCloudGuardTarget.cloneResource(resource, 'cloud_guard_target') as OciCloudGuardTarget
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciCloudGuardTarget): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciCloudGuardTarget, parentId: string): OciCloudGuardTarget {
        return resource
    }
    export function getConnectionIds(resource: OciCloudGuardTarget, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciCloudGuardTargetClient extends AutoGenerated.OciCloudGuardTargetClient {
    static new(): OciCloudGuardTarget {
        return OciCloudGuardTarget.newResource()
    }
    static clone(resource: OciCloudGuardTarget): OciCloudGuardTarget {
        return OciCloudGuardTarget.cloneResource(resource)
    }
}

export default OciCloudGuardTargetClient
