/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciCloudBridgeAgentPlugin.js"

export interface OciCloudBridgeAgentPlugin extends AutoGenerated.OciCloudBridgeAgentPlugin {}

export namespace OciCloudBridgeAgentPlugin {

    export function newResource(type?: string): OciCloudBridgeAgentPlugin {
        const resource = {
            ...AutoGenerated.OciCloudBridgeAgentPlugin.newResource('cloud_bridge_agent_plugin'),
        }
        return resource
    }
    export function cloneResource(resource: OciCloudBridgeAgentPlugin, type?: string): OciCloudBridgeAgentPlugin {
        return AutoGenerated.OciCloudBridgeAgentPlugin.cloneResource(resource, 'cloud_bridge_agent_plugin') as OciCloudBridgeAgentPlugin
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciCloudBridgeAgentPlugin): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciCloudBridgeAgentPlugin, parentId: string): OciCloudBridgeAgentPlugin {
        return resource
    }
    export function getConnectionIds(resource: OciCloudBridgeAgentPlugin, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciCloudBridgeAgentPluginClient extends AutoGenerated.OciCloudBridgeAgentPluginClient {
    static new(): OciCloudBridgeAgentPlugin {
        return OciCloudBridgeAgentPlugin.newResource()
    }
    static clone(resource: OciCloudBridgeAgentPlugin): OciCloudBridgeAgentPlugin {
        return OciCloudBridgeAgentPlugin.cloneResource(resource)
    }
}

export default OciCloudBridgeAgentPluginClient
