/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciContainerengineAddon.js"

export interface OciContainerengineAddon extends AutoGenerated.OciContainerengineAddon {}

export namespace OciContainerengineAddon {
    
    export function newResource(type?: string): OciContainerengineAddon {
        const resource = {
            ...AutoGenerated.OciContainerengineAddon.newResource('containerengine_addon'),
        }
        return resource
    }
    export function cloneResource(resource: OciContainerengineAddon, type?: string): OciContainerengineAddon {
        return AutoGenerated.OciContainerengineAddon.cloneResource(resource, 'containerengine_addon') as OciContainerengineAddon
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciContainerengineAddon): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciContainerengineAddon, parentId: string): OciContainerengineAddon {
        return resource
    }
    export function getConnectionIds(resource: OciContainerengineAddon, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciContainerengineAddonClient extends AutoGenerated.OciContainerengineAddonClient {
    static new(): OciContainerengineAddon {
        return OciContainerengineAddon.newResource()
    }
    static clone(resource: OciContainerengineAddon): OciContainerengineAddon {
        return OciContainerengineAddon.cloneResource(resource)
    }
}

export default OciContainerengineAddonClient
