/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDatabaseSoftwareImage.js"

export interface OciDatabaseSoftwareImage extends AutoGenerated.OciDatabaseSoftwareImage {}

export namespace OciDatabaseSoftwareImage {
    
    export function newResource(type?: string): OciDatabaseSoftwareImage {
        const resource = {
            ...AutoGenerated.OciDatabaseSoftwareImage.newResource('database_software_image'),
        }
        return resource
    }
    export function cloneResource(resource: OciDatabaseSoftwareImage, type?: string): OciDatabaseSoftwareImage {
        return AutoGenerated.OciDatabaseSoftwareImage.cloneResource(resource, 'database_software_image') as OciDatabaseSoftwareImage
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDatabaseSoftwareImage): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDatabaseSoftwareImage, parentId: string): OciDatabaseSoftwareImage {
        return resource
    }
    export function getConnectionIds(resource: OciDatabaseSoftwareImage, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDatabaseSoftwareImageClient extends AutoGenerated.OciDatabaseSoftwareImageClient {
    static new(): OciDatabaseSoftwareImage {
        return OciDatabaseSoftwareImage.newResource()
    }
    static clone(resource: OciDatabaseSoftwareImage): OciDatabaseSoftwareImage {
        return OciDatabaseSoftwareImage.cloneResource(resource)
    }
}

export default OciDatabaseSoftwareImageClient
