/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDataSafeUserAssessment.js"

export interface OciDataSafeUserAssessment extends AutoGenerated.OciDataSafeUserAssessment {}

export namespace OciDataSafeUserAssessment {
    
    export function newResource(type?: string): OciDataSafeUserAssessment {
        const resource = {
            ...AutoGenerated.OciDataSafeUserAssessment.newResource('data_safe_user_assessment'),
        }
        return resource
    }
    export function cloneResource(resource: OciDataSafeUserAssessment, type?: string): OciDataSafeUserAssessment {
        return AutoGenerated.OciDataSafeUserAssessment.cloneResource(resource, 'data_safe_user_assessment') as OciDataSafeUserAssessment
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDataSafeUserAssessment): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDataSafeUserAssessment, parentId: string): OciDataSafeUserAssessment {
        return resource
    }
    export function getConnectionIds(resource: OciDataSafeUserAssessment, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDataSafeUserAssessmentClient extends AutoGenerated.OciDataSafeUserAssessmentClient {
    static new(): OciDataSafeUserAssessment {
        return OciDataSafeUserAssessment.newResource()
    }
    static clone(resource: OciDataSafeUserAssessment): OciDataSafeUserAssessment {
        return OciDataSafeUserAssessment.cloneResource(resource)
    }
}

export default OciDataSafeUserAssessmentClient
