/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDataSafeSecurityAssessment.js"

export interface OciDataSafeSecurityAssessment extends AutoGenerated.OciDataSafeSecurityAssessment {}

export namespace OciDataSafeSecurityAssessment {
    
    export function newResource(type?: string): OciDataSafeSecurityAssessment {
        const resource = {
            ...AutoGenerated.OciDataSafeSecurityAssessment.newResource('data_safe_security_assessment'),
        }
        return resource
    }
    export function cloneResource(resource: OciDataSafeSecurityAssessment, type?: string): OciDataSafeSecurityAssessment {
        return AutoGenerated.OciDataSafeSecurityAssessment.cloneResource(resource, 'data_safe_security_assessment') as OciDataSafeSecurityAssessment
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDataSafeSecurityAssessment): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDataSafeSecurityAssessment, parentId: string): OciDataSafeSecurityAssessment {
        return resource
    }
    export function getConnectionIds(resource: OciDataSafeSecurityAssessment, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDataSafeSecurityAssessmentClient extends AutoGenerated.OciDataSafeSecurityAssessmentClient {
    static new(): OciDataSafeSecurityAssessment {
        return OciDataSafeSecurityAssessment.newResource()
    }
    static clone(resource: OciDataSafeSecurityAssessment): OciDataSafeSecurityAssessment {
        return OciDataSafeSecurityAssessment.cloneResource(resource)
    }
}

export default OciDataSafeSecurityAssessmentClient
