/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDnsResolverEndpoint.js"

export interface OciDnsResolverEndpoint extends AutoGenerated.OciDnsResolverEndpoint {}

export namespace OciDnsResolverEndpoint {
    
    export function newResource(type?: string): OciDnsResolverEndpoint {
        const resource = {
            ...AutoGenerated.OciDnsResolverEndpoint.newResource('dns_resolver_endpoint'),
        }
        return resource
    }
    export function cloneResource(resource: OciDnsResolverEndpoint, type?: string): OciDnsResolverEndpoint {
        return AutoGenerated.OciDnsResolverEndpoint.cloneResource(resource, 'dns_resolver_endpoint') as OciDnsResolverEndpoint
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDnsResolverEndpoint): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDnsResolverEndpoint, parentId: string): OciDnsResolverEndpoint {
        return resource
    }
    export function getConnectionIds(resource: OciDnsResolverEndpoint, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDnsResolverEndpointClient extends AutoGenerated.OciDnsResolverEndpointClient {
    static new(): OciDnsResolverEndpoint {
        return OciDnsResolverEndpoint.newResource()
    }
    static clone(resource: OciDnsResolverEndpoint): OciDnsResolverEndpoint {
        return OciDnsResolverEndpoint.cloneResource(resource)
    }
}

export default OciDnsResolverEndpointClient
