/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDatabaseMigration.js"

export interface OciDatabaseMigration extends AutoGenerated.OciDatabaseMigration {}

export namespace OciDatabaseMigration {
    
    export function newResource(type?: string): OciDatabaseMigration {
        const resource = {
            ...AutoGenerated.OciDatabaseMigration.newResource('database_migration'),
        }
        return resource
    }
    export function cloneResource(resource: OciDatabaseMigration, type?: string): OciDatabaseMigration {
        return AutoGenerated.OciDatabaseMigration.cloneResource(resource, 'database_migration') as OciDatabaseMigration
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDatabaseMigration): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDatabaseMigration, parentId: string): OciDatabaseMigration {
        return resource
    }
    export function getConnectionIds(resource: OciDatabaseMigration, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDatabaseMigrationClient extends AutoGenerated.OciDatabaseMigrationClient {
    static new(): OciDatabaseMigration {
        return OciDatabaseMigration.newResource()
    }
    static clone(resource: OciDatabaseMigration): OciDatabaseMigration {
        return OciDatabaseMigration.cloneResource(resource)
    }
}

export default OciDatabaseMigrationClient
