/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDevopsRepository.js"

export interface OciDevopsRepository extends AutoGenerated.OciDevopsRepository {}

export namespace OciDevopsRepository {
    export namespace MirrorRepositoryConfig {
        export interface MirrorRepositoryConfig extends AutoGenerated.OciDevopsRepository.MirrorRepositoryConfig.MirrorRepositoryConfig {}
        export function newMirrorRepositoryConfig(): MirrorRepositoryConfig {return AutoGenerated.OciDevopsRepository.MirrorRepositoryConfig.newMirrorRepositoryConfig()}
        export namespace TriggerSchedule {
            export interface TriggerSchedule extends AutoGenerated.OciDevopsRepository.MirrorRepositoryConfig.TriggerSchedule.TriggerSchedule {}
            export function newTriggerSchedule(): TriggerSchedule {return AutoGenerated.OciDevopsRepository.MirrorRepositoryConfig.TriggerSchedule.newTriggerSchedule()}
            
        }
    }
    export function newResource(type?: string): OciDevopsRepository {
        const resource = {
            ...AutoGenerated.OciDevopsRepository.newResource('devops_repository'),
        }
        return resource
    }
    export function cloneResource(resource: OciDevopsRepository, type?: string): OciDevopsRepository {
        return AutoGenerated.OciDevopsRepository.cloneResource(resource, 'devops_repository') as OciDevopsRepository
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDevopsRepository): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDevopsRepository, parentId: string): OciDevopsRepository {
        return resource
    }
    export function getConnectionIds(resource: OciDevopsRepository, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDevopsRepositoryClient extends AutoGenerated.OciDevopsRepositoryClient {
    static new(): OciDevopsRepository {
        return OciDevopsRepository.newResource()
    }
    static clone(resource: OciDevopsRepository): OciDevopsRepository {
        return OciDevopsRepository.cloneResource(resource)
    }
}

export default OciDevopsRepositoryClient
