/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDevopsBuildPipeline.js"

export interface OciDevopsBuildPipeline extends AutoGenerated.OciDevopsBuildPipeline {}

export namespace OciDevopsBuildPipeline {
    export namespace BuildPipelineParameters {
        export interface BuildPipelineParameters extends AutoGenerated.OciDevopsBuildPipeline.BuildPipelineParameters.BuildPipelineParameters {}
        export function newBuildPipelineParameters(): BuildPipelineParameters {return AutoGenerated.OciDevopsBuildPipeline.BuildPipelineParameters.newBuildPipelineParameters()}
        export namespace Items {
            export interface Items extends AutoGenerated.OciDevopsBuildPipeline.BuildPipelineParameters.Items.Items {}
            export function newItems(): Items {return AutoGenerated.OciDevopsBuildPipeline.BuildPipelineParameters.Items.newItems()}
            
        }
    }
    export function newResource(type?: string): OciDevopsBuildPipeline {
        const resource = {
            ...AutoGenerated.OciDevopsBuildPipeline.newResource('devops_build_pipeline'),
        }
        return resource
    }
    export function cloneResource(resource: OciDevopsBuildPipeline, type?: string): OciDevopsBuildPipeline {
        return AutoGenerated.OciDevopsBuildPipeline.cloneResource(resource, 'devops_build_pipeline') as OciDevopsBuildPipeline
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDevopsBuildPipeline): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDevopsBuildPipeline, parentId: string): OciDevopsBuildPipeline {
        return resource
    }
    export function getConnectionIds(resource: OciDevopsBuildPipeline, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDevopsBuildPipelineClient extends AutoGenerated.OciDevopsBuildPipelineClient {
    static new(): OciDevopsBuildPipeline {
        return OciDevopsBuildPipeline.newResource()
    }
    static clone(resource: OciDevopsBuildPipeline): OciDevopsBuildPipeline {
        return OciDevopsBuildPipeline.cloneResource(resource)
    }
}

export default OciDevopsBuildPipelineClient
