/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDevopsConnection.js"

export interface OciDevopsConnection extends AutoGenerated.OciDevopsConnection {}

export namespace OciDevopsConnection {
    export namespace TlsVerifyConfig {
        export interface TlsVerifyConfig extends AutoGenerated.OciDevopsConnection.TlsVerifyConfig.TlsVerifyConfig {}
        export function newTlsVerifyConfig(): TlsVerifyConfig {return AutoGenerated.OciDevopsConnection.TlsVerifyConfig.newTlsVerifyConfig()}
        
    }
    export function newResource(type?: string): OciDevopsConnection {
        const resource = {
            ...AutoGenerated.OciDevopsConnection.newResource('devops_connection'),
        }
        return resource
    }
    export function cloneResource(resource: OciDevopsConnection, type?: string): OciDevopsConnection {
        return AutoGenerated.OciDevopsConnection.cloneResource(resource, 'devops_connection') as OciDevopsConnection
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDevopsConnection): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDevopsConnection, parentId: string): OciDevopsConnection {
        return resource
    }
    export function getConnectionIds(resource: OciDevopsConnection, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDevopsConnectionClient extends AutoGenerated.OciDevopsConnectionClient {
    static new(): OciDevopsConnection {
        return OciDevopsConnection.newResource()
    }
    static clone(resource: OciDevopsConnection): OciDevopsConnection {
        return OciDevopsConnection.cloneResource(resource)
    }
}

export default OciDevopsConnectionClient
