/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDatascienceJob.js"

export interface OciDatascienceJob extends AutoGenerated.OciDatascienceJob {}

export namespace OciDatascienceJob {
    export namespace JobInfrastructureConfigurationDetails {
        export interface JobInfrastructureConfigurationDetails extends AutoGenerated.OciDatascienceJob.JobInfrastructureConfigurationDetails.JobInfrastructureConfigurationDetails {}
        export function newJobInfrastructureConfigurationDetails(): JobInfrastructureConfigurationDetails {return AutoGenerated.OciDatascienceJob.JobInfrastructureConfigurationDetails.newJobInfrastructureConfigurationDetails()}
        
    }
    export function newResource(type?: string): OciDatascienceJob {
        const resource = {
            ...AutoGenerated.OciDatascienceJob.newResource('datascience_job'),
        }
        return resource
    }
    export function cloneResource(resource: OciDatascienceJob, type?: string): OciDatascienceJob {
        return AutoGenerated.OciDatascienceJob.cloneResource(resource, 'datascience_job') as OciDatascienceJob
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDatascienceJob): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDatascienceJob, parentId: string): OciDatascienceJob {
        return resource
    }
    export function getConnectionIds(resource: OciDatascienceJob, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDatascienceJobClient extends AutoGenerated.OciDatascienceJobClient {
    static new(): OciDatascienceJob {
        return OciDatascienceJob.newResource()
    }
    static clone(resource: OciDatascienceJob): OciDatascienceJob {
        return OciDatascienceJob.cloneResource(resource)
    }
}

export default OciDatascienceJobClient
