/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDnsSteeringPolicy.js"

export interface OciDnsSteeringPolicy extends AutoGenerated.OciDnsSteeringPolicy {}

export namespace OciDnsSteeringPolicy {
    export namespace Answers {
        export interface Answers extends AutoGenerated.OciDnsSteeringPolicy.Answers.Answers {}
        export function newAnswers(): Answers {return AutoGenerated.OciDnsSteeringPolicy.Answers.newAnswers()}
        
    }
    export namespace Rules {
        export interface Rules extends AutoGenerated.OciDnsSteeringPolicy.Rules.Rules {}
        export function newRules(): Rules {return AutoGenerated.OciDnsSteeringPolicy.Rules.newRules()}
        
    }
    export function newResource(type?: string): OciDnsSteeringPolicy {
        const resource = {
            ...AutoGenerated.OciDnsSteeringPolicy.newResource('dns_steering_policy'),
        }
        return resource
    }
    export function cloneResource(resource: OciDnsSteeringPolicy, type?: string): OciDnsSteeringPolicy {
        return AutoGenerated.OciDnsSteeringPolicy.cloneResource(resource, 'dns_steering_policy') as OciDnsSteeringPolicy
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDnsSteeringPolicy): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDnsSteeringPolicy, parentId: string): OciDnsSteeringPolicy {
        return resource
    }
    export function getConnectionIds(resource: OciDnsSteeringPolicy, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDnsSteeringPolicyClient extends AutoGenerated.OciDnsSteeringPolicyClient {
    static new(): OciDnsSteeringPolicy {
        return OciDnsSteeringPolicy.newResource()
    }
    static clone(resource: OciDnsSteeringPolicy): OciDnsSteeringPolicy {
        return OciDnsSteeringPolicy.cloneResource(resource)
    }
}

export default OciDnsSteeringPolicyClient
