/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciDnsTsigKey.js"

export interface OciDnsTsigKey extends AutoGenerated.OciDnsTsigKey {}

export namespace OciDnsTsigKey {
    
    export function newResource(type?: string): OciDnsTsigKey {
        const resource = {
            ...AutoGenerated.OciDnsTsigKey.newResource('dns_tsig_key'),
        }
        return resource
    }
    export function cloneResource(resource: OciDnsTsigKey, type?: string): OciDnsTsigKey {
        return AutoGenerated.OciDnsTsigKey.cloneResource(resource, 'dns_tsig_key') as OciDnsTsigKey
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciDnsTsigKey): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciDnsTsigKey, parentId: string): OciDnsTsigKey {
        return resource
    }
    export function getConnectionIds(resource: OciDnsTsigKey, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciDnsTsigKeyClient extends AutoGenerated.OciDnsTsigKeyClient {
    static new(): OciDnsTsigKey {
        return OciDnsTsigKey.newResource()
    }
    static clone(resource: OciDnsTsigKey): OciDnsTsigKey {
        return OciDnsTsigKey.cloneResource(resource)
    }
}

export default OciDnsTsigKeyClient
