/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciFunctionsApplication.js"

export interface OciFunctionsApplication extends AutoGenerated.OciFunctionsApplication {}

export namespace OciFunctionsApplication {
    export namespace ImagePolicyConfig {
        export interface ImagePolicyConfig extends AutoGenerated.OciFunctionsApplication.ImagePolicyConfig.ImagePolicyConfig {}
        export function newImagePolicyConfig(): ImagePolicyConfig {return AutoGenerated.OciFunctionsApplication.ImagePolicyConfig.newImagePolicyConfig()}
        
    }
    export namespace TraceConfig {
        export interface TraceConfig extends AutoGenerated.OciFunctionsApplication.TraceConfig.TraceConfig {}
        export function newTraceConfig(): TraceConfig {return AutoGenerated.OciFunctionsApplication.TraceConfig.newTraceConfig()}
        
    }
    export function newResource(type?: string): OciFunctionsApplication {
        const resource = {
            ...AutoGenerated.OciFunctionsApplication.newResource('functions_application'),
        }
        return resource
    }
    export function cloneResource(resource: OciFunctionsApplication, type?: string): OciFunctionsApplication {
        return AutoGenerated.OciFunctionsApplication.cloneResource(resource, 'functions_application') as OciFunctionsApplication
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciFunctionsApplication): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciFunctionsApplication, parentId: string): OciFunctionsApplication {
        return resource
    }
    export function getConnectionIds(resource: OciFunctionsApplication, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciFunctionsApplicationClient extends AutoGenerated.OciFunctionsApplicationClient {
    static new(): OciFunctionsApplication {
        return OciFunctionsApplication.newResource()
    }
    static clone(resource: OciFunctionsApplication): OciFunctionsApplication {
        return OciFunctionsApplication.cloneResource(resource)
    }
}

export default OciFunctionsApplicationClient
