/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciFunctionsFunction.js"

export interface OciFunctionsFunction extends AutoGenerated.OciFunctionsFunction {}

export namespace OciFunctionsFunction {
    export namespace SourceDetails {
        export interface SourceDetails extends AutoGenerated.OciFunctionsFunction.SourceDetails.SourceDetails {}
        export function newSourceDetails(): SourceDetails {return AutoGenerated.OciFunctionsFunction.SourceDetails.newSourceDetails()}
        
    }
    export namespace TraceConfig {
        export interface TraceConfig extends AutoGenerated.OciFunctionsFunction.TraceConfig.TraceConfig {}
        export function newTraceConfig(): TraceConfig {return AutoGenerated.OciFunctionsFunction.TraceConfig.newTraceConfig()}
        
    }
    export function newResource(type?: string): OciFunctionsFunction {
        const resource = {
            ...AutoGenerated.OciFunctionsFunction.newResource('functions_function'),
        }
        return resource
    }
    export function cloneResource(resource: OciFunctionsFunction, type?: string): OciFunctionsFunction {
        return AutoGenerated.OciFunctionsFunction.cloneResource(resource, 'functions_function') as OciFunctionsFunction
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciFunctionsFunction): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciFunctionsFunction, parentId: string): OciFunctionsFunction {
        return resource
    }
    export function getConnectionIds(resource: OciFunctionsFunction, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciFunctionsFunctionClient extends AutoGenerated.OciFunctionsFunctionClient {
    static new(): OciFunctionsFunction {
        return OciFunctionsFunction.newResource()
    }
    static clone(resource: OciFunctionsFunction): OciFunctionsFunction {
        return OciFunctionsFunction.cloneResource(resource)
    }
}

export default OciFunctionsFunctionClient
