/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciGenaiDedicatedCluster.js"

export interface OciGenaiDedicatedCluster extends AutoGenerated.OciGenaiDedicatedCluster {}

export namespace OciGenaiDedicatedCluster {
    
    export function newResource(type?: string): OciGenaiDedicatedCluster {
        const resource = {
            ...AutoGenerated.OciGenaiDedicatedCluster.newResource('genai_dedicated_cluster'),
        }
        return resource
    }
    export function cloneResource(resource: OciGenaiDedicatedCluster, type?: string): OciGenaiDedicatedCluster {
        return AutoGenerated.OciGenaiDedicatedCluster.cloneResource(resource, 'genai_dedicated_cluster') as OciGenaiDedicatedCluster
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciGenaiDedicatedCluster): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciGenaiDedicatedCluster, parentId: string): OciGenaiDedicatedCluster {
        return resource
    }
    export function getConnectionIds(resource: OciGenaiDedicatedCluster, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciGenaiDedicatedClusterClient extends AutoGenerated.OciGenaiDedicatedClusterClient {
    static new(): OciGenaiDedicatedCluster {
        return OciGenaiDedicatedCluster.newResource()
    }
    static clone(resource: OciGenaiDedicatedCluster): OciGenaiDedicatedCluster {
        return OciGenaiDedicatedCluster.cloneResource(resource)
    }
}

export default OciGenaiDedicatedClusterClient
