/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciHealthChecksHttpMonitor.js"

export interface OciHealthChecksHttpMonitor extends AutoGenerated.OciHealthChecksHttpMonitor {}

export namespace OciHealthChecksHttpMonitor {
    
    export function newResource(type?: string): OciHealthChecksHttpMonitor {
        const resource = {
            ...AutoGenerated.OciHealthChecksHttpMonitor.newResource('health_checks_http_monitor'),
        }
        return resource
    }
    export function cloneResource(resource: OciHealthChecksHttpMonitor, type?: string): OciHealthChecksHttpMonitor {
        return AutoGenerated.OciHealthChecksHttpMonitor.cloneResource(resource, 'health_checks_http_monitor') as OciHealthChecksHttpMonitor
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciHealthChecksHttpMonitor): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciHealthChecksHttpMonitor, parentId: string): OciHealthChecksHttpMonitor {
        return resource
    }
    export function getConnectionIds(resource: OciHealthChecksHttpMonitor, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciHealthChecksHttpMonitorClient extends AutoGenerated.OciHealthChecksHttpMonitorClient {
    static new(): OciHealthChecksHttpMonitor {
        return OciHealthChecksHttpMonitor.newResource()
    }
    static clone(resource: OciHealthChecksHttpMonitor): OciHealthChecksHttpMonitor {
        return OciHealthChecksHttpMonitor.cloneResource(resource)
    }
}

export default OciHealthChecksHttpMonitorClient
