/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciIntegrationInstance.js"

export interface OciIntegrationInstance extends AutoGenerated.OciIntegrationInstance {}

export namespace OciIntegrationInstance {
    
    export function newResource(type?: string): OciIntegrationInstance {
        const resource = {
            ...AutoGenerated.OciIntegrationInstance.newResource('integration_instance'),
        }
        return resource
    }
    export function cloneResource(resource: OciIntegrationInstance, type?: string): OciIntegrationInstance {
        return AutoGenerated.OciIntegrationInstance.cloneResource(resource, 'integration_instance') as OciIntegrationInstance
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciIntegrationInstance): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciIntegrationInstance, parentId: string): OciIntegrationInstance {
        return resource
    }
    export function getConnectionIds(resource: OciIntegrationInstance, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciIntegrationInstanceClient extends AutoGenerated.OciIntegrationInstanceClient {
    static new(): OciIntegrationInstance {
        return OciIntegrationInstance.newResource()
    }
    static clone(resource: OciIntegrationInstance): OciIntegrationInstance {
        return OciIntegrationInstance.cloneResource(resource)
    }
}

export default OciIntegrationInstanceClient
