/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciLoadBalancer"

export interface OciLoadBalancer extends AutoGenerated.OciLoadBalancer {}

export interface OciReservedIps extends AutoGenerated.OciReservedIps {}

export interface OciShapeDetails extends AutoGenerated.OciShapeDetails {}

export namespace OciLoadBalancer {
    
    export interface OciReservedIps extends AutoGenerated.OciLoadBalancer.OciReservedIps {}

    export interface OciShapeDetails extends AutoGenerated.OciLoadBalancer.OciShapeDetails {}

    export function newResource(type?: string): OciLoadBalancer {
        return {
            ...AutoGenerated.OciLoadBalancer.newResource('load_balancer'),
        }
    }
    export function cloneResource(resource: OciLoadBalancer, type?: string): OciLoadBalancer {
        return AutoGenerated.OciLoadBalancer.cloneResource(resource, 'load_balancer') as OciLoadBalancer
    }
    export function allowedParentTypes(): string[] {
        console.debug('OciLoadBalancer: Allowed Parent Types')
        return ['Subnet']
    }
    export function getParentId(resource: OciLoadBalancer): string {
        console.debug('OciLoadBalancer: Getting Parent Id to for', resource.displayName, resource.id)
        let parentId = resource.subnetIds.length && resource.subnetIds[0] !== '' ? resource.subnetIds[0] as string  : resource.compartmentId as string
        return parentId
    }
    export function setParentId(resource: OciLoadBalancer, parentId: string): OciLoadBalancer {
        console.debug('OciLoadBalancer: Setting Parent Id to', parentId, 'for', resource.displayName, resource.id)
        resource.subnetIds[0] = parentId
        return resource
    }
    export function getConnectionIds(resource: OciLoadBalancer): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        console.debug('OciLoadBalancer: Getting Connection Ids to for', resource.displayName, resource.id)
        return resource.subnetIds.slice(1)
    }
    
    export function newOciReservedIps(): OciReservedIps {
        return {
            ...AutoGenerated.OciLoadBalancer.newOciReservedIps(),
        }
    }

    export function newOciShapeDetails(): OciShapeDetails {
        return {
            ...AutoGenerated.OciLoadBalancer.newOciShapeDetails(),
        }
    }

}

export class OciLoadBalancerClient {
    static new(): OciLoadBalancer {
        return OciLoadBalancer.newResource()
    }
    static clone(resource: OciLoadBalancer): OciLoadBalancer {
        return OciLoadBalancer.cloneResource(resource)
    }
}

export default OciLoadBalancerClient
