/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciLoadBalancerRuleSet.js"

export interface OciLoadBalancerRuleSet extends AutoGenerated.OciLoadBalancerRuleSet {}

export namespace OciLoadBalancerRuleSet {
    export namespace Items {
        export interface Items extends AutoGenerated.OciLoadBalancerRuleSet.Items.Items {}
        export function newItems(): Items {return AutoGenerated.OciLoadBalancerRuleSet.Items.newItems()}
        export namespace Conditions {
            export interface Conditions extends AutoGenerated.OciLoadBalancerRuleSet.Items.Conditions.Conditions {}
            export function newConditions(): Conditions {return AutoGenerated.OciLoadBalancerRuleSet.Items.Conditions.newConditions()}
            
        }
        export namespace RedirectUri {
            export interface RedirectUri extends AutoGenerated.OciLoadBalancerRuleSet.Items.RedirectUri.RedirectUri {}
            export function newRedirectUri(): RedirectUri {return AutoGenerated.OciLoadBalancerRuleSet.Items.RedirectUri.newRedirectUri()}
            
        }
    }
    export function newResource(type?: string): OciLoadBalancerRuleSet {
        const resource = {
            ...AutoGenerated.OciLoadBalancerRuleSet.newResource('load_balancer_rule_set'),
        }
        return resource
    }
    export function cloneResource(resource: OciLoadBalancerRuleSet, type?: string): OciLoadBalancerRuleSet {
        return AutoGenerated.OciLoadBalancerRuleSet.cloneResource(resource, 'load_balancer_rule_set') as OciLoadBalancerRuleSet
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciLoadBalancerRuleSet): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciLoadBalancerRuleSet, parentId: string): OciLoadBalancerRuleSet {
        return resource
    }
    export function getConnectionIds(resource: OciLoadBalancerRuleSet, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciLoadBalancerRuleSetClient extends AutoGenerated.OciLoadBalancerRuleSetClient {
    static new(): OciLoadBalancerRuleSet {
        return OciLoadBalancerRuleSet.newResource()
    }
    static clone(resource: OciLoadBalancerRuleSet): OciLoadBalancerRuleSet {
        return OciLoadBalancerRuleSet.cloneResource(resource)
    }
}

export default OciLoadBalancerRuleSetClient
