/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciLoadBalancerListener"

export interface OciLoadBalancerListener extends AutoGenerated.OciLoadBalancerListener {}

export namespace OciLoadBalancerListener {
    
    export function newResource(type?: string): OciLoadBalancerListener {
        return {
            ...AutoGenerated.OciLoadBalancerListener.newResource('load_balancer_listener'),
        }
    }
    export function cloneResource(resource: OciLoadBalancerListener, type?: string): OciLoadBalancerListener {
        return AutoGenerated.OciLoadBalancerListener.cloneResource(resource, 'load_balancer_listener') as OciLoadBalancerListener
    }
    export function allowedParentTypes(): string[] {
        console.debug('OciLoadBalancerListener: Allowed Parent Types')
        return []
    }
    export function getParentId(resource: OciLoadBalancerListener): string {
        console.debug('OciLoadBalancerListener: Getting Parent Id to for', resource.displayName, resource.id)
        return resource.compartmentId
    }
    export function setParentId(resource: OciLoadBalancerListener, parentId: string): OciLoadBalancerListener {
        console.debug('OciLoadBalancerListener: Setting Parent Id to', parentId, 'for', resource.displayName, resource.id)
        return resource
    }
    export function getConnectionIds(resource: OciLoadBalancerListener): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        console.debug('OciLoadBalancerListener: Getting Connection Ids to for', resource.displayName, resource.id)
        return []
    }
    
}

export class OciLoadBalancerListenerClient {
    static new(): OciLoadBalancerListener {
        return OciLoadBalancerListener.newResource()
    }
    static clone(resource: OciLoadBalancerListener): OciLoadBalancerListener {
        return OciLoadBalancerListener.cloneResource(resource)
    }
}

export default OciLoadBalancerListenerClient
