/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciLogAnalyticsEntity.js"

export interface OciLogAnalyticsEntity extends AutoGenerated.OciLogAnalyticsEntity {}

export namespace OciLogAnalyticsEntity {
    export function newResource(type?: string): OciLogAnalyticsEntity {
        const resource = {
            ...AutoGenerated.OciLogAnalyticsEntity.newResource('log_analytics_entity'),
        }
        return resource
    }
    export function cloneResource(resource: OciLogAnalyticsEntity, type?: string): OciLogAnalyticsEntity {
        return AutoGenerated.OciLogAnalyticsEntity.cloneResource(resource, 'log_analytics_entity') as OciLogAnalyticsEntity
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciLogAnalyticsEntity): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciLogAnalyticsEntity, parentId: string): OciLogAnalyticsEntity {
        return resource
    }
    export function getConnectionIds(resource: OciLogAnalyticsEntity, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciLogAnalyticsEntityClient extends AutoGenerated.OciLogAnalyticsEntityClient {
    static new(): OciLogAnalyticsEntity {
        return OciLogAnalyticsEntity.newResource()
    }
    static clone(resource: OciLogAnalyticsEntity): OciLogAnalyticsEntity {
        return OciLogAnalyticsEntity.cloneResource(resource)
    }
}

export default OciLogAnalyticsEntityClient
