/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciMysqlReplica.js"

export interface OciMysqlReplica extends AutoGenerated.OciMysqlReplica {}

export namespace OciMysqlReplica {
    export namespace ReplicaOverrides {
        export interface ReplicaOverrides extends AutoGenerated.OciMysqlReplica.ReplicaOverrides.ReplicaOverrides {}
        export function newReplicaOverrides(): ReplicaOverrides {return AutoGenerated.OciMysqlReplica.ReplicaOverrides.newReplicaOverrides()}
        
    }
    export function newResource(type?: string): OciMysqlReplica {
        const resource = {
            ...AutoGenerated.OciMysqlReplica.newResource('mysql_replica'),
        }
        return resource
    }
    export function cloneResource(resource: OciMysqlReplica, type?: string): OciMysqlReplica {
        return AutoGenerated.OciMysqlReplica.cloneResource(resource, 'mysql_replica') as OciMysqlReplica
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciMysqlReplica): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciMysqlReplica, parentId: string): OciMysqlReplica {
        return resource
    }
    export function getConnectionIds(resource: OciMysqlReplica, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciMysqlReplicaClient extends AutoGenerated.OciMysqlReplicaClient {
    static new(): OciMysqlReplica {
        return OciMysqlReplica.newResource()
    }
    static clone(resource: OciMysqlReplica): OciMysqlReplica {
        return OciMysqlReplica.cloneResource(resource)
    }
}

export default OciMysqlReplicaClient
