/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign"
import * as AutoGenerated from "./generated/OciMountTarget"

export interface OciMountTarget extends AutoGenerated.OciMountTarget {}

export namespace OciMountTarget {
    
    export function newResource(type?: string): OciMountTarget {
        const resource = {
            ...AutoGenerated.OciMountTarget.newResource('mount_target'),
        }
        return resource
    }
    export function cloneResource(resource: OciMountTarget, type?: string): OciMountTarget {
        return AutoGenerated.OciMountTarget.cloneResource(resource, 'mount_target') as OciMountTarget
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciMountTarget): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciMountTarget, parentId: string): OciMountTarget {
        return resource
    }
    export function getConnectionIds(resource: OciMountTarget, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciMountTargetClient extends AutoGenerated.OciMountTargetClient {
    static new(): OciMountTarget {
        return OciMountTarget.newResource()
    }
    static clone(resource: OciMountTarget): OciMountTarget {
        return OciMountTarget.cloneResource(resource)
    }
}

export default OciMountTargetClient
