/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciNetworkFirewallPolicy.js"

export interface OciNetworkFirewallPolicy extends AutoGenerated.OciNetworkFirewallPolicy {}

export namespace OciNetworkFirewallPolicy {
    
    export function newResource(type?: string): OciNetworkFirewallPolicy {
        const resource = {
            ...AutoGenerated.OciNetworkFirewallPolicy.newResource('network_firewall_policy'),
        }
        return resource
    }
    export function cloneResource(resource: OciNetworkFirewallPolicy, type?: string): OciNetworkFirewallPolicy {
        return AutoGenerated.OciNetworkFirewallPolicy.cloneResource(resource, 'network_firewall_policy') as OciNetworkFirewallPolicy
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciNetworkFirewallPolicy): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciNetworkFirewallPolicy, parentId: string): OciNetworkFirewallPolicy {
        return resource
    }
    export function getConnectionIds(resource: OciNetworkFirewallPolicy, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciNetworkFirewallPolicyClient extends AutoGenerated.OciNetworkFirewallPolicyClient {
    static new(): OciNetworkFirewallPolicy {
        return OciNetworkFirewallPolicy.newResource()
    }
    static clone(resource: OciNetworkFirewallPolicy): OciNetworkFirewallPolicy {
        return OciNetworkFirewallPolicy.cloneResource(resource)
    }
}

export default OciNetworkFirewallPolicyClient
