/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciNetworkLoadBalancerBackendSet.js"

export interface OciNetworkLoadBalancerBackendSet extends AutoGenerated.OciNetworkLoadBalancerBackendSet {}

export namespace OciNetworkLoadBalancerBackendSet {
    export namespace HealthChecker {
        export interface HealthChecker extends AutoGenerated.OciNetworkLoadBalancerBackendSet.HealthChecker.HealthChecker {}
        export function newHealthChecker(): HealthChecker {return AutoGenerated.OciNetworkLoadBalancerBackendSet.HealthChecker.newHealthChecker()}
        
    }
    export function newResource(type?: string): OciNetworkLoadBalancerBackendSet {
        const resource = {
            ...AutoGenerated.OciNetworkLoadBalancerBackendSet.newResource('network_load_balancer_backend_set'),
        }
        return resource
    }
    export function cloneResource(resource: OciNetworkLoadBalancerBackendSet, type?: string): OciNetworkLoadBalancerBackendSet {
        return AutoGenerated.OciNetworkLoadBalancerBackendSet.cloneResource(resource, 'network_load_balancer_backend_set') as OciNetworkLoadBalancerBackendSet
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciNetworkLoadBalancerBackendSet): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciNetworkLoadBalancerBackendSet, parentId: string): OciNetworkLoadBalancerBackendSet {
        return resource
    }
    export function getConnectionIds(resource: OciNetworkLoadBalancerBackendSet, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciNetworkLoadBalancerBackendSetClient extends AutoGenerated.OciNetworkLoadBalancerBackendSetClient {
    static new(): OciNetworkLoadBalancerBackendSet {
        return OciNetworkLoadBalancerBackendSet.newResource()
    }
    static clone(resource: OciNetworkLoadBalancerBackendSet): OciNetworkLoadBalancerBackendSet {
        return OciNetworkLoadBalancerBackendSet.cloneResource(resource)
    }
}

export default OciNetworkLoadBalancerBackendSetClient
