/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciOpsiAwrHub.js"

export interface OciOpsiAwrHub extends AutoGenerated.OciOpsiAwrHub {}

export namespace OciOpsiAwrHub {
    
    export function newResource(type?: string): OciOpsiAwrHub {
        const resource = {
            ...AutoGenerated.OciOpsiAwrHub.newResource('opsi_awr_hub'),
        }
        return resource
    }
    export function cloneResource(resource: OciOpsiAwrHub, type?: string): OciOpsiAwrHub {
        return AutoGenerated.OciOpsiAwrHub.cloneResource(resource, 'opsi_awr_hub') as OciOpsiAwrHub
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciOpsiAwrHub): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciOpsiAwrHub, parentId: string): OciOpsiAwrHub {
        return resource
    }
    export function getConnectionIds(resource: OciOpsiAwrHub, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciOpsiAwrHubClient extends AutoGenerated.OciOpsiAwrHubClient {
    static new(): OciOpsiAwrHub {
        return OciOpsiAwrHub.newResource()
    }
    static clone(resource: OciOpsiAwrHub): OciOpsiAwrHub {
        return OciOpsiAwrHub.cloneResource(resource)
    }
}

export default OciOpsiAwrHubClient
