/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciOpsiDatabaseInsight.js"

export interface OciOpsiDatabaseInsight extends AutoGenerated.OciOpsiDatabaseInsight {}

export namespace OciOpsiDatabaseInsight {
    export namespace ConnectionDetails {
        export interface ConnectionDetails extends AutoGenerated.OciOpsiDatabaseInsight.ConnectionDetails.ConnectionDetails {}
        export function newConnectionDetails(): ConnectionDetails {return AutoGenerated.OciOpsiDatabaseInsight.ConnectionDetails.newConnectionDetails()}
        
    }
    export namespace CredentialDetails {
        export interface CredentialDetails extends AutoGenerated.OciOpsiDatabaseInsight.CredentialDetails.CredentialDetails {}
        export function newCredentialDetails(): CredentialDetails {return AutoGenerated.OciOpsiDatabaseInsight.CredentialDetails.newCredentialDetails()}
        
    }
    export function newResource(type?: string): OciOpsiDatabaseInsight {
        const resource = {
            ...AutoGenerated.OciOpsiDatabaseInsight.newResource('opsi_database_insight'),
        }
        return resource
    }
    export function cloneResource(resource: OciOpsiDatabaseInsight, type?: string): OciOpsiDatabaseInsight {
        return AutoGenerated.OciOpsiDatabaseInsight.cloneResource(resource, 'opsi_database_insight') as OciOpsiDatabaseInsight
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciOpsiDatabaseInsight): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciOpsiDatabaseInsight, parentId: string): OciOpsiDatabaseInsight {
        return resource
    }
    export function getConnectionIds(resource: OciOpsiDatabaseInsight, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciOpsiDatabaseInsightClient extends AutoGenerated.OciOpsiDatabaseInsightClient {
    static new(): OciOpsiDatabaseInsight {
        return OciOpsiDatabaseInsight.newResource()
    }
    static clone(resource: OciOpsiDatabaseInsight): OciOpsiDatabaseInsight {
        return OciOpsiDatabaseInsight.cloneResource(resource)
    }
}

export default OciOpsiDatabaseInsightClient
