/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciObjectstorageObject.js"

export interface OciObjectstorageObject extends AutoGenerated.OciObjectstorageObject {}

export namespace OciObjectstorageObject {
    
    export function newResource(type?: string): OciObjectstorageObject {
        const resource = {
            ...AutoGenerated.OciObjectstorageObject.newResource('objectstorage_object'),
        }
        return resource
    }
    export function cloneResource(resource: OciObjectstorageObject, type?: string): OciObjectstorageObject {
        return AutoGenerated.OciObjectstorageObject.cloneResource(resource, 'objectstorage_object') as OciObjectstorageObject
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciObjectstorageObject): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciObjectstorageObject, parentId: string): OciObjectstorageObject {
        return resource
    }
    export function getConnectionIds(resource: OciObjectstorageObject, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciObjectstorageObjectClient extends AutoGenerated.OciObjectstorageObjectClient {
    static new(): OciObjectstorageObject {
        return OciObjectstorageObject.newResource()
    }
    static clone(resource: OciObjectstorageObject): OciObjectstorageObject {
        return OciObjectstorageObject.cloneResource(resource)
    }
}

export default OciObjectstorageObjectClient
