/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciOdaInstance.js"

export interface OciOdaInstance extends AutoGenerated.OciOdaInstance {}

export namespace OciOdaInstance {
    
    export function newResource(type?: string): OciOdaInstance {
        const resource = {
            ...AutoGenerated.OciOdaInstance.newResource('oda_instance'),
        }
        return resource
    }
    export function cloneResource(resource: OciOdaInstance, type?: string): OciOdaInstance {
        return AutoGenerated.OciOdaInstance.cloneResource(resource, 'oda_instance') as OciOdaInstance
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciOdaInstance): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciOdaInstance, parentId: string): OciOdaInstance {
        return resource
    }
    export function getConnectionIds(resource: OciOdaInstance, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciOdaInstanceClient extends AutoGenerated.OciOdaInstanceClient {
    static new(): OciOdaInstance {
        return OciOdaInstance.newResource()
    }
    static clone(resource: OciOdaInstance): OciOdaInstance {
        return OciOdaInstance.cloneResource(resource)
    }
}

export default OciOdaInstanceClient
