/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciPreauthenticatedRequest.js"

export interface OciPreauthenticatedRequest extends AutoGenerated.OciPreauthenticatedRequest {}

export namespace OciPreauthenticatedRequest {
    
    export function newResource(type?: string): OciPreauthenticatedRequest {
        const resource = {
            ...AutoGenerated.OciPreauthenticatedRequest.newResource('preauthenticated_request'),
        }
        return resource
    }
    export function cloneResource(resource: OciPreauthenticatedRequest, type?: string): OciPreauthenticatedRequest {
        return AutoGenerated.OciPreauthenticatedRequest.cloneResource(resource, 'preauthenticated_request') as OciPreauthenticatedRequest
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciPreauthenticatedRequest): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciPreauthenticatedRequest, parentId: string): OciPreauthenticatedRequest {
        return resource
    }
    export function getConnectionIds(resource: OciPreauthenticatedRequest, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciPreauthenticatedRequestClient extends AutoGenerated.OciPreauthenticatedRequestClient {
    static new(): OciPreauthenticatedRequest {
        return OciPreauthenticatedRequest.newResource()
    }
    static clone(resource: OciPreauthenticatedRequest): OciPreauthenticatedRequest {
        return OciPreauthenticatedRequest.cloneResource(resource)
    }
}

export default OciPreauthenticatedRequestClient
