/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciRouteTableAttachment.js"

export interface OciRouteTableAttachment extends AutoGenerated.OciRouteTableAttachment {}

export namespace OciRouteTableAttachment {
    
    export function newResource(type?: string): OciRouteTableAttachment {
        const resource = {
            ...AutoGenerated.OciRouteTableAttachment.newResource('route_table_attachment'),
        }
        return resource
    }
    export function cloneResource(resource: OciRouteTableAttachment, type?: string): OciRouteTableAttachment {
        return AutoGenerated.OciRouteTableAttachment.cloneResource(resource, 'route_table_attachment') as OciRouteTableAttachment
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciRouteTableAttachment): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciRouteTableAttachment, parentId: string): OciRouteTableAttachment {
        return resource
    }
    export function getConnectionIds(resource: OciRouteTableAttachment, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciRouteTableAttachmentClient extends AutoGenerated.OciRouteTableAttachmentClient {
    static new(): OciRouteTableAttachment {
        return OciRouteTableAttachment.newResource()
    }
    static clone(resource: OciRouteTableAttachment): OciRouteTableAttachment {
        return OciRouteTableAttachment.cloneResource(resource)
    }
}

export default OciRouteTableAttachmentClient
