/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciServiceMesh.js"

export interface OciServiceMesh extends AutoGenerated.OciServiceMesh {}

export namespace OciServiceMesh {
    export namespace CertificateAuthorities {
        export interface CertificateAuthorities extends AutoGenerated.OciServiceMesh.CertificateAuthorities.CertificateAuthorities {}
        export function newCertificateAuthorities(): CertificateAuthorities {return AutoGenerated.OciServiceMesh.CertificateAuthorities.newCertificateAuthorities()}
        
    }
    export namespace Mtls {
        export interface Mtls extends AutoGenerated.OciServiceMesh.Mtls.Mtls {}
        export function newMtls(): Mtls {return AutoGenerated.OciServiceMesh.Mtls.newMtls()}
        
    }
    export function newResource(type?: string): OciServiceMesh {
        const resource = {
            ...AutoGenerated.OciServiceMesh.newResource('service_mesh'),
        }
        return resource
    }
    export function cloneResource(resource: OciServiceMesh, type?: string): OciServiceMesh {
        return AutoGenerated.OciServiceMesh.cloneResource(resource, 'service_mesh') as OciServiceMesh
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciServiceMesh): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciServiceMesh, parentId: string): OciServiceMesh {
        return resource
    }
    export function getConnectionIds(resource: OciServiceMesh, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciServiceMeshClient extends AutoGenerated.OciServiceMeshClient {
    static new(): OciServiceMesh {
        return OciServiceMesh.newResource()
    }
    static clone(resource: OciServiceMesh): OciServiceMesh {
        return OciServiceMesh.cloneResource(resource)
    }
}

export default OciServiceMeshClient
