/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciServiceConnector.js"

export interface OciServiceConnector extends AutoGenerated.OciServiceConnector {}

export namespace OciServiceConnector {
    
    export function newResource(type?: string): OciServiceConnector {
        const resource = {
            ...AutoGenerated.OciServiceConnector.newResource('service_connector'),
        }
        return resource
    }
    export function cloneResource(resource: OciServiceConnector, type?: string): OciServiceConnector {
        return AutoGenerated.OciServiceConnector.cloneResource(resource, 'service_connector') as OciServiceConnector
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciServiceConnector): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciServiceConnector, parentId: string): OciServiceConnector {
        return resource
    }
    export function getConnectionIds(resource: OciServiceConnector, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciServiceConnectorClient extends AutoGenerated.OciServiceConnectorClient {
    static new(): OciServiceConnector {
        return OciServiceConnector.newResource()
    }
    static clone(resource: OciServiceConnector): OciServiceConnector {
        return OciServiceConnector.cloneResource(resource)
    }
}

export default OciServiceConnectorClient
