/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciStackMonitoringConfig.js"

export interface OciStackMonitoringConfig extends AutoGenerated.OciStackMonitoringConfig {}

export namespace OciStackMonitoringConfig {
    
    export function newResource(type?: string): OciStackMonitoringConfig {
        const resource = {
            ...AutoGenerated.OciStackMonitoringConfig.newResource('stack_monitoring_config'),
        }
        return resource
    }
    export function cloneResource(resource: OciStackMonitoringConfig, type?: string): OciStackMonitoringConfig {
        return AutoGenerated.OciStackMonitoringConfig.cloneResource(resource, 'stack_monitoring_config') as OciStackMonitoringConfig
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciStackMonitoringConfig): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciStackMonitoringConfig, parentId: string): OciStackMonitoringConfig {
        return resource
    }
    export function getConnectionIds(resource: OciStackMonitoringConfig, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciStackMonitoringConfigClient extends AutoGenerated.OciStackMonitoringConfigClient {
    static new(): OciStackMonitoringConfig {
        return OciStackMonitoringConfig.newResource()
    }
    static clone(resource: OciStackMonitoringConfig): OciStackMonitoringConfig {
        return OciStackMonitoringConfig.cloneResource(resource)
    }
}

export default OciStackMonitoringConfigClient
