/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciServiceCatalog.js"

export interface OciServiceCatalog extends AutoGenerated.OciServiceCatalog {}

export namespace OciServiceCatalog {
    
    export function newResource(type?: string): OciServiceCatalog {
        const resource = {
            ...AutoGenerated.OciServiceCatalog.newResource('service_catalog'),
        }
        return resource
    }
    export function cloneResource(resource: OciServiceCatalog, type?: string): OciServiceCatalog {
        return AutoGenerated.OciServiceCatalog.cloneResource(resource, 'service_catalog') as OciServiceCatalog
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciServiceCatalog): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciServiceCatalog, parentId: string): OciServiceCatalog {
        return resource
    }
    export function getConnectionIds(resource: OciServiceCatalog, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciServiceCatalogClient extends AutoGenerated.OciServiceCatalogClient {
    static new(): OciServiceCatalog {
        return OciServiceCatalog.newResource()
    }
    static clone(resource: OciServiceCatalog): OciServiceCatalog {
        return OciServiceCatalog.cloneResource(resource)
    }
}

export default OciServiceCatalogClient
