/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciTag.js"

export interface OciTag extends AutoGenerated.OciTag {}

export namespace OciTag {
    
    export function newResource(type?: string): OciTag {
        const resource = {
            ...AutoGenerated.OciTag.newResource('tag'),
        }
        return resource
    }
    export function cloneResource(resource: OciTag, type?: string): OciTag {
        return AutoGenerated.OciTag.cloneResource(resource, 'tag') as OciTag
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciTag): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciTag, parentId: string): OciTag {
        return resource
    }
    export function getConnectionIds(resource: OciTag, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciTagClient extends AutoGenerated.OciTagClient {
    static new(): OciTag {
        return OciTag.newResource()
    }
    static clone(resource: OciTag): OciTag {
        return OciTag.cloneResource(resource)
    }
}

export default OciTagClient
