/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciVisualBuilderInstance.js"

export interface OciVisualBuilderInstance extends AutoGenerated.OciVisualBuilderInstance {}

export namespace OciVisualBuilderInstance {
    export namespace CustomEndpoint {
        export interface CustomEndpoint extends AutoGenerated.OciVisualBuilderInstance.CustomEndpoint.CustomEndpoint {}
        export function newCustomEndpoint(): CustomEndpoint {return AutoGenerated.OciVisualBuilderInstance.CustomEndpoint.newCustomEndpoint()}
        
    }
    export function newResource(type?: string): OciVisualBuilderInstance {
        const resource = {
            ...AutoGenerated.OciVisualBuilderInstance.newResource('visual_builder_instance'),
        }
        return resource
    }
    export function cloneResource(resource: OciVisualBuilderInstance, type?: string): OciVisualBuilderInstance {
        return AutoGenerated.OciVisualBuilderInstance.cloneResource(resource, 'visual_builder_instance') as OciVisualBuilderInstance
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciVisualBuilderInstance): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciVisualBuilderInstance, parentId: string): OciVisualBuilderInstance {
        return resource
    }
    export function getConnectionIds(resource: OciVisualBuilderInstance, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciVisualBuilderInstanceClient extends AutoGenerated.OciVisualBuilderInstanceClient {
    static new(): OciVisualBuilderInstance {
        return OciVisualBuilderInstance.newResource()
    }
    static clone(resource: OciVisualBuilderInstance): OciVisualBuilderInstance {
        return OciVisualBuilderInstance.cloneResource(resource)
    }
}

export default OciVisualBuilderInstanceClient
