/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciVirtualCircuit.js"

export interface OciVirtualCircuit extends AutoGenerated.OciVirtualCircuit {}

export namespace OciVirtualCircuit {
    export namespace CrossConnectMappings {
        export interface CrossConnectMappings extends AutoGenerated.OciVirtualCircuit.CrossConnectMappings.CrossConnectMappings {}
        export function newCrossConnectMappings(): CrossConnectMappings {return AutoGenerated.OciVirtualCircuit.CrossConnectMappings.newCrossConnectMappings()}
        
    }
    export namespace PublicPrefixes {
        export interface PublicPrefixes extends AutoGenerated.OciVirtualCircuit.PublicPrefixes.PublicPrefixes {}
        export function newPublicPrefixes(): PublicPrefixes {return AutoGenerated.OciVirtualCircuit.PublicPrefixes.newPublicPrefixes()}
        
    }
    export function newResource(type?: string): OciVirtualCircuit {
        const resource = {
            ...AutoGenerated.OciVirtualCircuit.newResource('virtual_circuit'),
        }
        return resource
    }
    export function cloneResource(resource: OciVirtualCircuit, type?: string): OciVirtualCircuit {
        return AutoGenerated.OciVirtualCircuit.cloneResource(resource, 'virtual_circuit') as OciVirtualCircuit
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciVirtualCircuit): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciVirtualCircuit, parentId: string): OciVirtualCircuit {
        return resource
    }
    export function getConnectionIds(resource: OciVirtualCircuit, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciVirtualCircuitClient extends AutoGenerated.OciVirtualCircuitClient {
    static new(): OciVirtualCircuit {
        return OciVirtualCircuit.newResource()
    }
    static clone(resource: OciVirtualCircuit): OciVirtualCircuit {
        return OciVirtualCircuit.cloneResource(resource)
    }
}

export default OciVirtualCircuitClient
