/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciVlan.js"

export interface OciVlan extends AutoGenerated.OciVlan {}

export namespace OciVlan {
    
    export function newResource(type?: string): OciVlan {
        const resource = {
            ...AutoGenerated.OciVlan.newResource('vlan'),
        }
        return resource
    }
    export function cloneResource(resource: OciVlan, type?: string): OciVlan {
        return AutoGenerated.OciVlan.cloneResource(resource, 'vlan') as OciVlan
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciVlan): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciVlan, parentId: string): OciVlan {
        return resource
    }
    export function getConnectionIds(resource: OciVlan, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciVlanClient extends AutoGenerated.OciVlanClient {
    static new(): OciVlan {
        return OciVlan.newResource()
    }
    static clone(resource: OciVlan): OciVlan {
        return OciVlan.cloneResource(resource)
    }
}

export default OciVlanClient
