/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciVolumeBackup.js"

export interface OciVolumeBackup extends AutoGenerated.OciVolumeBackup {}

export namespace OciVolumeBackup {
    export namespace SourceDetails {
        export interface SourceDetails extends AutoGenerated.OciVolumeBackup.SourceDetails.SourceDetails {}
        export function newSourceDetails(): SourceDetails {return AutoGenerated.OciVolumeBackup.SourceDetails.newSourceDetails()}
        
    }
    export function newResource(type?: string): OciVolumeBackup {
        const resource = {
            ...AutoGenerated.OciVolumeBackup.newResource('volume_backup'),
        }
        return resource
    }
    export function cloneResource(resource: OciVolumeBackup, type?: string): OciVolumeBackup {
        return AutoGenerated.OciVolumeBackup.cloneResource(resource, 'volume_backup') as OciVolumeBackup
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciVolumeBackup): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciVolumeBackup, parentId: string): OciVolumeBackup {
        return resource
    }
    export function getConnectionIds(resource: OciVolumeBackup, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciVolumeBackupClient extends AutoGenerated.OciVolumeBackupClient {
    static new(): OciVolumeBackup {
        return OciVolumeBackup.newResource()
    }
    static clone(resource: OciVolumeBackup): OciVolumeBackup {
        return OciVolumeBackup.cloneResource(resource)
    }
}

export default OciVolumeBackupClient
