/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciVnicAttachment"

export interface OciVnicAttachment extends AutoGenerated.OciVnicAttachment {}

export interface OciCreateVnicDetails extends AutoGenerated.OciCreateVnicDetails {}

export namespace OciVnicAttachment {
    
    export interface OciCreateVnicDetails extends AutoGenerated.OciVnicAttachment.OciCreateVnicDetails {}

    export function newResource(type?: string): OciVnicAttachment {
        return {
            ...AutoGenerated.OciVnicAttachment.newResource('vnic_attachment'),
        }
    }
    export function cloneResource(resource: OciVnicAttachment, type?: string): OciVnicAttachment {
        return AutoGenerated.OciVnicAttachment.cloneResource(resource, 'vnic_attachment') as OciVnicAttachment
    }
    export function allowedParentTypes(): string[] {
        console.debug('OciVnicAttachment: Allowed Parent Types')
        return []
    }
    export function getParentId(resource: OciVnicAttachment): string {
        console.debug('OciVnicAttachment: Getting Parent Id to for', resource.displayName, resource.id)
        return resource.compartmentId
    }
    export function setParentId(resource: OciVnicAttachment, parentId: string): OciVnicAttachment {
        console.debug('OciVnicAttachment: Setting Parent Id to', parentId, 'for', resource.displayName, resource.id)
        return resource
    }
    export function getConnectionIds(resource: OciVnicAttachment): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        console.debug('OciVnicAttachment: Getting Connection Ids to for', resource.displayName, resource.id)
        return []
    }
    
    export function newOciCreateVnicDetails(): OciCreateVnicDetails {
        return {
            ...AutoGenerated.OciVnicAttachment.newOciCreateVnicDetails(),
        }
    }

}

export class OciVnicAttachmentClient {
    static new(): OciVnicAttachment {
        return OciVnicAttachment.newResource()
    }
    static clone(resource: OciVnicAttachment): OciVnicAttachment {
        return OciVnicAttachment.cloneResource(resource)
    }
}

export default OciVnicAttachmentClient
