/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign"
import * as AutoGenerated from "./generated/OciVolumeAttachment"

export interface OciVolumeAttachment extends AutoGenerated.OciVolumeAttachment {}

export namespace OciVolumeAttachment {
    
    export function newResource(type?: string): OciVolumeAttachment {
        const resource = {
            ...AutoGenerated.OciVolumeAttachment.newResource('volume_attachment'),
        }
        return resource
    }
    export function cloneResource(resource: OciVolumeAttachment, type?: string): OciVolumeAttachment {
        return AutoGenerated.OciVolumeAttachment.cloneResource(resource, 'volume_attachment') as OciVolumeAttachment
    }
    export function allowedParentTypes(): string[] {
        return ['Instance']
    }
    export function getParentId(resource: OciVolumeAttachment): string {
        const parentId = resource.instanceId !== '' ? resource.instanceId : resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciVolumeAttachment, parentId: string): OciVolumeAttachment {
        resource.instanceId = parentId
        return resource
    }
    export function getConnectionIds(resource: OciVolumeAttachment, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciVolumeAttachmentClient extends AutoGenerated.OciVolumeAttachmentClient {
    static new(): OciVolumeAttachment {
        return OciVolumeAttachment.newResource()
    }
    static clone(resource: OciVolumeAttachment): OciVolumeAttachment {
        return OciVolumeAttachment.cloneResource(resource)
    }
}

export default OciVolumeAttachmentClient
