/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/OciWaaPolicy.js"

export interface OciWaaPolicy extends AutoGenerated.OciWaaPolicy {}

export namespace OciWaaPolicy {
    export namespace ResponseCachingPolicy {
        export interface ResponseCachingPolicy extends AutoGenerated.OciWaaPolicy.ResponseCachingPolicy.ResponseCachingPolicy {}
        export function newResponseCachingPolicy(): ResponseCachingPolicy {return AutoGenerated.OciWaaPolicy.ResponseCachingPolicy.newResponseCachingPolicy()}
        
    }
    export namespace ResponseCompressionPolicy {
        export interface ResponseCompressionPolicy extends AutoGenerated.OciWaaPolicy.ResponseCompressionPolicy.ResponseCompressionPolicy {}
        export function newResponseCompressionPolicy(): ResponseCompressionPolicy {return AutoGenerated.OciWaaPolicy.ResponseCompressionPolicy.newResponseCompressionPolicy()}
        export namespace GzipCompression {
            export interface GzipCompression extends AutoGenerated.OciWaaPolicy.ResponseCompressionPolicy.GzipCompression.GzipCompression {}
            export function newGzipCompression(): GzipCompression {return AutoGenerated.OciWaaPolicy.ResponseCompressionPolicy.GzipCompression.newGzipCompression()}
            
        }
    }
    export function newResource(type?: string): OciWaaPolicy {
        const resource = {
            ...AutoGenerated.OciWaaPolicy.newResource('waa_policy'),
        }
        return resource
    }
    export function cloneResource(resource: OciWaaPolicy, type?: string): OciWaaPolicy {
        return AutoGenerated.OciWaaPolicy.cloneResource(resource, 'waa_policy') as OciWaaPolicy
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: OciWaaPolicy): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: OciWaaPolicy, parentId: string): OciWaaPolicy {
        return resource
    }
    export function getConnectionIds(resource: OciWaaPolicy, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class OciWaaPolicyClient extends AutoGenerated.OciWaaPolicyClient {
    static new(): OciWaaPolicy {
        return OciWaaPolicy.newResource()
    }
    static clone(resource: OciWaaPolicy): OciWaaPolicy {
        return OciWaaPolicy.cloneResource(resource)
    }
}

export default OciWaaPolicyClient
