/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciDrgRouteDistributionStatement"

export interface OciDrgRouteDistributionStatement extends AutoGenerated.OciDrgRouteDistributionStatement {}

export interface OciMatchCriteria extends AutoGenerated.OciMatchCriteria {}

export namespace OciDrgRouteDistributionStatement {
    export function newResource(type?: string): OciDrgRouteDistributionStatement {
        return {
            ...AutoGenerated.OciDrgRouteDistributionStatement.newResource('drg_route_distribution_statement'),
        }
    }
    
    export function newOciMatchCriteria(): OciMatchCriteria {
        return {
            ...AutoGenerated.OciDrgRouteDistributionStatement.newOciMatchCriteria(),
        }
    }

}

export class OciDrgRouteDistributionStatementClient {
    static new(): OciDrgRouteDistributionStatement {
        return OciDrgRouteDistributionStatement.newResource()
    }
}

export default OciDrgRouteDistributionStatementClient
