/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciLocalPeeringGateway"

export interface OciLocalPeeringGateway extends AutoGenerated.OciLocalPeeringGateway {}

export namespace OciLocalPeeringGateway {
    export function newResource(type?: string): OciLocalPeeringGateway {
        return {
            ...AutoGenerated.OciLocalPeeringGateway.newResource('local_peering_gateway'),
        }
    }
    
}

export class OciLocalPeeringGatewayClient {
    static new(): OciLocalPeeringGateway {
        return OciLocalPeeringGateway.newResource()
    }
}

export default OciLocalPeeringGatewayClient
