/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/GoogleOracleDatabaseAutonomousDatabase.js"

export interface GoogleOracleDatabaseAutonomousDatabase extends AutoGenerated.GoogleOracleDatabaseAutonomousDatabase {}

export namespace GoogleOracleDatabaseAutonomousDatabase {
    
    export function newResource(type?: string): GoogleOracleDatabaseAutonomousDatabase {
        const resource = {
            ...AutoGenerated.GoogleOracleDatabaseAutonomousDatabase.newResource('oracle_database_autonomous_database'),
        }
        return resource
    }
    export function cloneResource(resource: GoogleOracleDatabaseAutonomousDatabase, type?: string): GoogleOracleDatabaseAutonomousDatabase {
        return AutoGenerated.GoogleOracleDatabaseAutonomousDatabase.cloneResource(resource, 'oracle_database_autonomous_database') as GoogleOracleDatabaseAutonomousDatabase
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: GoogleOracleDatabaseAutonomousDatabase): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: GoogleOracleDatabaseAutonomousDatabase, parentId: string): GoogleOracleDatabaseAutonomousDatabase {
        return resource
    }
    export function getConnectionIds(resource: GoogleOracleDatabaseAutonomousDatabase, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class GoogleOracleDatabaseAutonomousDatabaseClient extends AutoGenerated.GoogleOracleDatabaseAutonomousDatabaseClient {
    static new(): GoogleOracleDatabaseAutonomousDatabase {
        return GoogleOracleDatabaseAutonomousDatabase.newResource()
    }
    static clone(resource: GoogleOracleDatabaseAutonomousDatabase): GoogleOracleDatabaseAutonomousDatabase {
        return GoogleOracleDatabaseAutonomousDatabase.cloneResource(resource)
    }
}

export default GoogleOracleDatabaseAutonomousDatabaseClient
