/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

/*
** Self-contained Google Compute Subnetwork model resource. Unlike the existing
** GoogleComputeNetwork (which extends an AutoGenerated.* codegen namespace),
** this resource has no generated layer, so the interface, fields and factory
** are all defined inline here — mirroring the AWS provider pattern.
*/

import { OcdResources } from "../../../OcdDesign.js"
import { GoogleResource } from "../GoogleResource.js"

export interface GoogleComputeSubnetwork extends GoogleResource {
    network: string
    ipCidrRange: string
    region: string
}

export namespace GoogleComputeSubnetwork {
    export function newResource(type: string = 'compute_subnetwork'): GoogleComputeSubnetwork {
        return {
            ...GoogleResource.newResource(type),
            network: '',
            ipCidrRange: '',
            region: ''
        } as GoogleComputeSubnetwork
    }
    export function cloneResource(resource: GoogleComputeSubnetwork, type: string = 'compute_subnetwork'): GoogleComputeSubnetwork {
        return GoogleResource.cloneResource(resource, type) as GoogleComputeSubnetwork
    }
    export function allowedParentTypes(): string[] {
        return ['ComputeNetwork']
    }
    export function getParentId(resource: GoogleComputeSubnetwork): string {
        return resource.network
    }
    export function setParentId(resource: GoogleComputeSubnetwork, parentId: string): GoogleComputeSubnetwork {
        resource.network = parentId
        return resource
    }
    export function getConnectionIds(resource: GoogleComputeSubnetwork, allResources: OcdResources): string[] {
        const associationIds: string[] = []
        return associationIds
    }
}

export class GoogleComputeSubnetworkClient {
    static new(): GoogleComputeSubnetwork {
        return GoogleComputeSubnetwork.newResource()
    }
    static clone(resource: GoogleComputeSubnetwork): GoogleComputeSubnetwork {
        return GoogleComputeSubnetwork.cloneResource(resource)
    }
}

export default GoogleComputeSubnetworkClient
