/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import { OcdResources } from "../../../OcdDesign.js"
import * as AutoGenerated from "./generated/GoogleOracleDatabaseCloudExadataInfrastructure.js"

export interface GoogleOracleDatabaseCloudExadataInfrastructure extends AutoGenerated.GoogleOracleDatabaseCloudExadataInfrastructure {}

export namespace GoogleOracleDatabaseCloudExadataInfrastructure {
    
    export function newResource(type?: string): GoogleOracleDatabaseCloudExadataInfrastructure {
        const resource = {
            ...AutoGenerated.GoogleOracleDatabaseCloudExadataInfrastructure.newResource('oracle_database_cloud_exadata_infrastructure'),
        }
        return resource
    }
    export function cloneResource(resource: GoogleOracleDatabaseCloudExadataInfrastructure, type?: string): GoogleOracleDatabaseCloudExadataInfrastructure {
        return AutoGenerated.GoogleOracleDatabaseCloudExadataInfrastructure.cloneResource(resource, 'oracle_database_cloud_exadata_infrastructure') as GoogleOracleDatabaseCloudExadataInfrastructure
    }
    export function allowedParentTypes(): string[] {
        return []
    }
    export function getParentId(resource: GoogleOracleDatabaseCloudExadataInfrastructure): string {
        const parentId = resource.compartmentId
        return parentId
    }
    export function setParentId(resource: GoogleOracleDatabaseCloudExadataInfrastructure, parentId: string): GoogleOracleDatabaseCloudExadataInfrastructure {
        return resource
    }
    export function getConnectionIds(resource: GoogleOracleDatabaseCloudExadataInfrastructure, allResources: OcdResources): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        let associationIds: string[] = []
        return associationIds
    }
}

export class GoogleOracleDatabaseCloudExadataInfrastructureClient extends AutoGenerated.GoogleOracleDatabaseCloudExadataInfrastructureClient {
    static new(): GoogleOracleDatabaseCloudExadataInfrastructure {
        return GoogleOracleDatabaseCloudExadataInfrastructure.newResource()
    }
    static clone(resource: GoogleOracleDatabaseCloudExadataInfrastructure): GoogleOracleDatabaseCloudExadataInfrastructure {
        return GoogleOracleDatabaseCloudExadataInfrastructure.cloneResource(resource)
    }
}

export default GoogleOracleDatabaseCloudExadataInfrastructureClient
