/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
    
import * as AutoGenerated from "./generated/OciDhcpOptions.js"
import { OciModelResources as Model } from '@ocd/model'
import { ExcelColumnProperties } from '../../../OcdExcelResource.js'
import { TableColumnProperties } from 'exceljs'

export class OciDhcpOptions extends AutoGenerated.OciDhcpOptions {
    resourceColumns = (): ExcelColumnProperties[] => {
        const columns: ExcelColumnProperties[] = [
            {header: 'VCN', key: 'vcnId', width: 30},
            {header: 'VCN Default', key: 'vcnDefault', width: 20},
        ]
        return columns
    }
    resourceTableColumns = (): TableColumnProperties[] => {
        const columns: TableColumnProperties[] = [
            {name: 'VCN', filterButton: true},
            {name: 'VCN Default', filterButton: true},
        ]   
        return columns
    }
    resourceRowGeneration = (resource: Model.OciDhcpOptions): any[] => [
        this.generateReferenceAttribute(resource.vcnId, this.allResources),
        resource.vcnDefault,
    ]
}

export default OciDhcpOptions
