/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
    
import * as AutoGenerated from "./generated/OciDevopsBuildPipeline.js"

export class OciDevopsBuildPipeline extends AutoGenerated.OciDevopsBuildPipeline {}

export default OciDevopsBuildPipeline
