/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
    
import * as AutoGenerated from "./generated/OciLocalPeeringGateway.js"
import { OciModelResources as Model } from '@ocd/model'
import { ExcelColumnProperties } from '../../../OcdExcelResource.js'
import { TableColumnProperties } from 'exceljs'

export class OciLocalPeeringGateway extends AutoGenerated.OciLocalPeeringGateway {
    resourceColumns = (): ExcelColumnProperties[] => {
        const columns: ExcelColumnProperties[] = [
            {header: 'VCN', key: 'vcnId', width: 30},
            {header: 'Route Table', key: 'routeTableId', width: 30},
        ]
        return columns
    }
    resourceTableColumns = (): TableColumnProperties[] => {
        const columns: TableColumnProperties[] = [
            {name: 'VCN', filterButton: true},
            {name: 'Route Table', filterButton: true},
        ]   
        return columns
    }
    resourceRowGeneration = (resource: Model.OciLocalPeeringGateway): any[] => [
        this.generateReferenceAttribute(resource.vcnId, this.allResources),
        this.generateReferenceAttribute(resource.routeTableId, this.allResources),
    ]
}

export default OciLocalPeeringGateway
