/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
    
import * as AutoGenerated from "./generated/OciVolume.js"
import { OciModelResources as Model } from '@ocd/model'
import { ExcelColumnProperties } from '../../../OcdExcelResource.js'
import { TableColumnProperties } from 'exceljs'

export class OciVolume extends AutoGenerated.OciVolume {
    resourceColumns = (): ExcelColumnProperties[] => {
        const columns: ExcelColumnProperties[] = [
            {header: 'VCN', key: 'vcnId', width: 30},
            {header: 'Size (Gbs)', key: 'sizeInGbs', width: 20},
        ]
        return columns
    }
    resourceTableColumns = (): TableColumnProperties[] => {
        const columns: TableColumnProperties[] = [
            {name: 'VCN', filterButton: true},
            {name: 'Size (Gbs)', filterButton: true},
        ]   
        return columns
    }
    resourceRowGeneration = (resource: Model.OciVolume): any[] => [
        this.generateReferenceAttribute(resource.vcnId, this.allResources),
        Number(resource.sizeInGbs),
    ]
}

export default OciVolume
