/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import OcdDocument from '../../../../OcdDocument'
import { ResourceElementConfig, ResourceProperties } from '../../../OcdPropertyTypes'
import * as AutoGenerated from './generated/OciLoadBalancerBackend'
import { OciLoadBalancerBackendConfigs } from './configs/OciLoadBalancerBackend'

export const OciLoadBalancerBackend = ({ ocdDocument, setOcdDocument, resource, summaryTitle, onDelete }: ResourceProperties): JSX.Element => {
    const configs: ResourceElementConfig[] = OciLoadBalancerBackendConfigs.configs()
    return (
        <AutoGenerated.OciLoadBalancerBackend ocdDocument={ocdDocument} setOcdDocument={(ocdDocument:OcdDocument) => setOcdDocument(ocdDocument)} resource={resource} configs={configs}summaryTitle={summaryTitle} onDelete={onDelete} />
    )
}
