/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import OcdDocument from '../../../../OcdDocument'
import { GeneratedResourceProperties, ResourceAdditionElements, ResourceElementConfig, ResourceProperties } from '../../../OcdPropertyTypes'
import * as AutoGenerated from './generated/OciNetworkSecurityGroup'
import { OciNetworkSecurityGroupConfigs } from './configs/OciNetworkSecurityGroup'
import { OciModelResources as Model } from '@ocd/model'
import { OciNetworkSecurityGroupSecurityRule } from './OciNetworkSecurityGroupSecurityRule'

export const OciNetworkSecurityGroup = ({ ocdDocument, setOcdDocument, resource }: ResourceProperties): JSX.Element => {
    const configs: ResourceElementConfig[] = OciNetworkSecurityGroupConfigs.configs()
    const additionalElements: ResourceAdditionElements[] = [{jsxElement: OciNetworkSecurityGroupSecurityRulesObjectList, afterElement: 'vcn_id'}]
    return (
        <AutoGenerated.OciNetworkSecurityGroup ocdDocument={ocdDocument} setOcdDocument={(ocdDocument:OcdDocument) => setOcdDocument(ocdDocument)} resource={resource} configs={configs} additionalElements={additionalElements} />
    )
}

export const OciNetworkSecurityGroupSecurityRulesObjectList = ({ ocdDocument, setOcdDocument, resource, configs, rootResource, additionalElements = [] }: GeneratedResourceProperties): JSX.Element => {
    const onClick = (e: React.MouseEvent<HTMLElement>) => {
        e.stopPropagation()
        e.preventDefault()
        const networkSecurityGroupSecurityRule = Model.OciNetworkSecurityGroupSecurityRule.newResource()
        Model.OciNetworkSecurityGroupSecurityRule.setParentId(networkSecurityGroupSecurityRule, rootResource.id)
        ocdDocument.addOciReasourceToList('network_security_group_security_rule', networkSecurityGroupSecurityRule)
        setOcdDocument(OcdDocument.clone(ocdDocument))
    }
    const onDelete = (child: Model.OciNetworkSecurityGroupSecurityRule) => {
        ocdDocument.removeResource(child.id)
        setOcdDocument(OcdDocument.clone(ocdDocument))
    }
    // @ts-ignore 
    return (
        <div className='ocd-property-row'>
            <details open={true}>
                <summary className='summary-background ocd-summary-row'><div>Security Rules</div><div className='add-property action-button-background action-button-column action-button' onClick={onClick}></div></summary>
                <div className='ocd-resource-properties'>
                    {ocdDocument.getOciResourceList('network_security_group_security_rule').filter((r: Model.OciNetworkSecurityGroupSecurityRule) => r.networkSecurityGroupId === resource.id).map((r: Model.OciNetworkSecurityGroupSecurityRule) => {return <OciNetworkSecurityGroupSecurityRulesObject ocdDocument={ocdDocument} setOcdDocument={(ocdDocument:OcdDocument) => setOcdDocument(ocdDocument)} resource={r} configs={configs} rootResource={rootResource} onDelete={onDelete} key={r.id}/>})}
                </div>
            </details>
        </div>
    )
}

export const OciNetworkSecurityGroupSecurityRulesObject = ({ ocdDocument, setOcdDocument, resource, configs, rootResource, onDelete, additionalElements = [] }: GeneratedResourceProperties): JSX.Element => {
    return (
        <div className='ocd-property-row'>
            <OciNetworkSecurityGroupSecurityRule ocdDocument={ocdDocument} setOcdDocument={(ocdDocument: OcdDocument) => setOcdDocument(ocdDocument)} resource={resource} rootResource={rootResource} summaryTitle='Rule' onDelete={onDelete} />
        </div>
    )
}
