# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#cloud-config
users:
  - default
  - name: prometheus
    homedir: /bin/false

write_files:
  # Wget Configuration
  - path: /etc/wgetrc
    append: true
    content: |
      #http_proxy = Add Proxy Here
      #https_proxy = Add Proxy Here
      #use_proxy = on
  # Add Node Export Service file
  - path: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target
  # Prometheus Config
  - path: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 10s

      scrape_configs:
        - job_name: 'Prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: 
                - localhost:9090

        - job_name: 'Node Exporters'
          file_sd_configs:
            - files:
              - '/etc/prometheus/targets.json'
  # Prometheus Targets
  - path: /etc/prometheus/targets.json
    content: |
      [
        {
          "labels": {
            "job": "Node Exporters"
          },
          "targets": [
            "linuxvm1.promprivsn.prometheusvcn.oraclevcn.com:9100",
            "linuxvm2.promprivsn.prometheusvcn.oraclevcn.com:9100"
          ]
        }
      ]

runcmd:
  - echo ">>> Creating Directory"
  - mkdir -p /run/install/prometheus
  - echo ">>> Getting Prometheus"
  - wget https://github.com/prometheus/prometheus/releases/download/v2.42.0/prometheus-2.42.0.linux-amd64.tar.gz -O /run/install/prometheus.tar.gz
  - echo ">>> Extracting Prometheus"
  - tar xvfz /run/install/prometheus.tar.gz -C /run/install/prometheus --strip-components=1
  - echo ">>> Moving Prometheus"
  - mkdir /etc/prometheus
  - mkdir /var/lib/prometheus
  - chown -R prometheus:prometheus /etc/prometheus
  - chown -R prometheus:prometheus /var/lib/prometheus
  - cp /run/install/prometheus/prometheus /usr/local/bin/
  - cp /run/install/prometheus/promtool /usr/local/bin/
  - chown prometheus:prometheus /usr/local/bin/prometheus
  - chown prometheus:prometheus /usr/local/bin/promtool
  - cp -r /run/install/prometheus/consoles /etc/prometheus
  - cp -r /run/install/prometheus/console_libraries /etc/prometheus
  - chown -R prometheus:prometheus /etc/prometheus/consoles
  - chown -R prometheus:prometheus /etc/prometheus/console_libraries
  - echo ">>> Starting Prometheus Service"
  - systemctl daemon-reload
  - systemctl start prometheus
  - systemctl enable prometheus
  - echo ">>> Configuring Firewall"
  - firewall-offline-cmd --add-port=9090/tcp
  - systemctl restart firewalld
  - echo "alias sshopc='/usr/bin/ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=10 -i ~/.ssh/id_rsa_opc'" >> /home/opc/.bashrc

final_message: "**** The system is finally up, after $UPTIME seconds ****"
