/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

/*
** Generator for the Operating Entities (OE) jsonnet string map consumed by the
** OCD Landing Zone Wizard.
**
** Walks the vendored OE sources at
**   ocd/packages/react/src/landingzone/oe/gen/**.{jsonnet,libsonnet}
** and emits a GENERATED `.ts` module exporting `OE_JSONNET_SOURCES`, a
** Record<string,string> keyed by the gen-relative path (e.g.
** 'landing_zone_multi.jsonnet', 'lib/collections.libsonnet').
**
** This mirrors the OciPriceListSnapshot.ts generated-string-map pattern so the
** sources survive the @ocd/react Vite library re-bundle (no import.meta.glob).
**
** Invocation (from the repo root or ocd/):
**   node scripts/generate_lz_jsonnet_sources.mjs
**   npm run generate-lz-jsonnet
**
** Upstream provenance is recorded in
**   ocd/packages/react/src/landingzone/oe/LICENSE.txt
*/

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..')
const sourcesManifestFile = path.join(repoRoot, 'ocd', 'packages', 'react', 'src', 'landingzone', 'OcdLzSources.json')
const genRoot = path.join(repoRoot, 'ocd', 'packages', 'react', 'src', 'landingzone', 'oe', 'gen')
const outFile = path.join(repoRoot, 'ocd', 'packages', 'react', 'src', 'landingzone', 'oe', 'OcdLandingZoneJsonnetSources.ts')

const SOURCE_EXTENSIONS = new Set(['.jsonnet', '.libsonnet'])

function getOperatingEntitiesSource() {
    const manifest = JSON.parse(readFileSync(sourcesManifestFile, 'utf-8'))
    const source = manifest.sources.find((s) => s.key === 'operating-entities')
    if (!source?.pinnedRef) {
        throw new Error(`Missing operating-entities pinnedRef in ${sourcesManifestFile}`)
    }
    return source
}

/** Recursively collect *.jsonnet / *.libsonnet files under dir. */
function collectSources(dir) {
    const found = []
    for (const entry of readdirSync(dir)) {
        const full = path.join(dir, entry)
        const stats = statSync(full)
        if (stats.isDirectory()) {
            found.push(...collectSources(full))
        } else if (SOURCE_EXTENSIONS.has(path.extname(entry))) {
            found.push(full)
        }
    }
    return found
}

function toGenRelativeKey(absPath) {
    // POSIX-style, gen-relative key regardless of host OS path separators.
    return path.relative(genRoot, absPath).split(path.sep).join('/')
}

function main() {
    const operatingEntitiesSource = getOperatingEntitiesSource()
    const files = collectSources(genRoot).sort()
    if (files.length === 0) {
        throw new Error(`No OE jsonnet sources found under ${genRoot}`)
    }

    const entries = files.map((absPath) => {
        const key = toGenRelativeKey(absPath)
        const source = readFileSync(absPath, 'utf-8')
        // JSON.stringify produces a safe, fully-escaped double-quoted JS string literal.
        return `    ${JSON.stringify(key)}: ${JSON.stringify(source)},`
    })

    const header = [
        '/*',
        '** Copyright (c) 2020, 2024, Oracle and/or its affiliates.',
        '** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.',
        '*/',
        '',
        '/*',
        '** GENERATED by scripts/generate_lz_jsonnet_sources.mjs - DO NOT EDIT BY HAND.',
        '**',
        '** Operating Entities (OE) jsonnet sources, bundled as a string map so they',
        '** survive the @ocd/react Vite library re-bundle and Electron asar packaging.',
        `** upstream: ${operatingEntitiesSource.repo} @ ${operatingEntitiesSource.pinnedRef} (UPL-1.0).`,
        '** Keys are gen-relative paths. Regenerate with:',
        '**     node scripts/generate_lz_jsonnet_sources.mjs',
        '*/',
        '',
        `export const OE_JSONNET_SOURCE_COUNT = ${files.length}`,
        '',
        'export const OE_JSONNET_SOURCES: Record<string, string> = {',
    ]

    const body = [...header, ...entries, '}', ''].join('\n')
    writeFileSync(outFile, body, 'utf-8')
    console.log(`Wrote ${files.length} OE jsonnet sources to ${path.relative(repoRoot, outFile)}`)
}

main()
