
# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

ARG BRANCH="master"
FROM oraclelinux:7-slim
LABEL "provider"="Oracle" \
      "issues"="https://github.com/oracle/oci-designer-toolkit/issues" \
      "version"="0.30.0" \
      "description"="OKIT Web Server Container." \
      "copyright"="Copyright (c) 2020, 2021, Oracle and/or its affiliates."
ENV PYTHONIOENCODING=utf8 \
    PYTHONPATH=":/okit/visualiser:/okit/okitweb:/okit" \
    FLASK_APP=okitweb \
    FLASK_DEBUG=1 \
    LANG=en_GB.UTF-8 \
    LANGUAGE=en_GB:en \
    LC_ALL=en_GB.UTF-8 \
    PATH=/root/bin:${PATH}
# Expose Ports
EXPOSE 80
EXPOSE 443
# Install new yum repos
RUN yum install -y \
    oracle-softwarecollection-release-el7 \
    oraclelinux-developer-release-el7 \
# Disable oci config repo
 && yum-config-manager --disable ol7_ociyum_config \
# Update base image
 && yum update -y \
# Install additional packages
 && yum install -y \
        git \
        openssl \
        python36 \
        python3-pip \
 && rm -rf /var/cache/yum \
# Upgrade pip
 && python3 -m pip install --upgrade pip \
# Install required python modules
 && python3 -m pip install --no-cache-dir \
        authlib \
        flask \
        gitpython \
        git-url-parse \
        gunicorn \
        oci \
        openpyxl \
        python-magic \
        pyyaml \
        requests \
# Create Workspace
 && mkdir -p /github \
 && git clone -c core.autocrlf=input https://github.com/oracle/oci-designer-toolkit.git /github/oci-designer-toolkit \
 && mkdir -p /okit/{git,local,log,instance/git,instance/local,instance/templates/user,workspace,ssl} \
 && mkdir -p /root/bin \
 && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /okit/ssl/okit.key -out /okit/ssl/okit.crt -subj "/C=GB/ST=Berkshire/L=Reading/O=Oracle/OU=OKIT/CN=www.oci_okit.com" \
 && ln -sv /github/oci-designer-toolkit/config /okit/config \
 && ln -sv /github/oci-designer-toolkit/okitweb /okit/okitweb \
 && ln -sv /github/oci-designer-toolkit/visualiser /okit/visualiser \
 && ln -sv /github/oci-designer-toolkit/okitweb/static/okit/templates/reference_architecture /okit/instance/templates/reference_architecture 
# Add entrypoint to automatically start webserver
ENTRYPOINT ["gunicorn", "okitweb.wsgi:app"]
CMD ["--config", "/okit/config/gunicorn_http.py"]
