/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
    
import * as AutoGenerated from "./generated/OciGoldenGateConnection.js"

export class OciGoldenGateConnection extends AutoGenerated.OciGoldenGateConnection {}

export default OciGoldenGateConnection
