/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import OcdDocument from '../../../../OcdDocument.js'
import { ResourceElementConfig, ResourceProperties } from '../../../OcdPropertyTypes.js'
import * as AutoGenerated from './generated/OciArtifactsContainerConfiguration.js'
import { OciArtifactsContainerConfigurationConfigs } from './configs/OciArtifactsContainerConfiguration.js'

export const OciArtifactsContainerConfiguration = ({ ocdDocument, setOcdDocument, resource }: ResourceProperties): JSX.Element => {
    const configs: ResourceElementConfig[] = OciArtifactsContainerConfigurationConfigs.configs()
    return (
        <AutoGenerated.OciArtifactsContainerConfiguration ocdDocument={ocdDocument} setOcdDocument={(ocdDocument:OcdDocument) => setOcdDocument(ocdDocument)} resource={resource} configs={configs} key={`${resource.id}.AutoGenerated.OciArtifactsContainerConfiguration`} />
    )
}
