/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import OcdDocument from '../../../../OcdDocument.js'
import { ResourceElementConfig, ResourceProperties } from '../../../OcdPropertyTypes.js'
import * as AutoGenerated from './generated/OciAdmRemediationRecipe.js'
import { OciAdmRemediationRecipeConfigs } from './configs/OciAdmRemediationRecipe.js'

export const OciAdmRemediationRecipe = ({ ocdDocument, setOcdDocument, resource }: ResourceProperties): JSX.Element => {
    const configs: ResourceElementConfig[] = OciAdmRemediationRecipeConfigs.configs()
    return (
        <AutoGenerated.OciAdmRemediationRecipe ocdDocument={ocdDocument} setOcdDocument={(ocdDocument:OcdDocument) => setOcdDocument(ocdDocument)} resource={resource} configs={configs} key={`${resource.id}.AutoGenerated.OciAdmRemediationRecipe`} />
    )
}
