/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import OcdDocument from '../../../../OcdDocument.js'
import { ResourceElementConfig, ResourceProperties } from '../../../OcdPropertyTypes.js'
import * as AutoGenerated from './generated/OciDataSafeTargetDatabase.js'
import { OciDataSafeTargetDatabaseConfigs } from './configs/OciDataSafeTargetDatabase.js'

export const OciDataSafeTargetDatabase = ({ ocdDocument, setOcdDocument, resource }: ResourceProperties): JSX.Element => {
    const configs: ResourceElementConfig[] = OciDataSafeTargetDatabaseConfigs.configs()
    return (
        <AutoGenerated.OciDataSafeTargetDatabase ocdDocument={ocdDocument} setOcdDocument={(ocdDocument:OcdDocument) => setOcdDocument(ocdDocument)} resource={resource} configs={configs} key={`${resource.id}.AutoGenerated.OciDataSafeTargetDatabase`} />
    )
}
