/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import OcdDocument from '../../../../OcdDocument.js'
import { ResourceElementConfig, ResourceProperties } from '../../../OcdPropertyTypes.js'
import * as AutoGenerated from './generated/OciObjectLifecyclePolicy.js'
import { OciObjectLifecyclePolicyConfigs } from './configs/OciObjectLifecyclePolicy.js'

export const OciObjectLifecyclePolicy = ({ ocdDocument, setOcdDocument, resource }: ResourceProperties): JSX.Element => {
    const configs: ResourceElementConfig[] = OciObjectLifecyclePolicyConfigs.configs()
    return (
        <AutoGenerated.OciObjectLifecyclePolicy ocdDocument={ocdDocument} setOcdDocument={(ocdDocument:OcdDocument) => setOcdDocument(ocdDocument)} resource={resource} configs={configs} key={`${resource.id}.AutoGenerated.OciObjectLifecyclePolicy`} />
    )
}
