/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciDrgAttachment"

export interface OciDrgAttachment extends AutoGenerated.OciDrgAttachment {}

export interface OciNetworkDetails extends AutoGenerated.OciNetworkDetails {}

export namespace OciDrgAttachment {
    export function newResource(type?: string): OciDrgAttachment {
        return {
            ...AutoGenerated.OciDrgAttachment.newResource('drg_attachment'),
        }
    }
    export function cloneResource(resource: OciDrgAttachment, type?: string): OciDrgAttachment {
        return {
            ...AutoGenerated.OciDrgAttachment.cloneResource(resource, 'drg_attachment'),
        }
    }
    
    export function newOciNetworkDetails(): OciNetworkDetails {
        return {
            ...AutoGenerated.OciDrgAttachment.newOciNetworkDetails(),
        }
    }

}

export class OciDrgAttachmentClient {
    static new(): OciDrgAttachment {
        return OciDrgAttachment.newResource()
    }
    static clone(resource: OciDrgAttachment): OciDrgAttachment {
        return OciDrgAttachment.cloneResource(resource)
    }
}

export default OciDrgAttachmentClient
