/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciInstance"

export interface OciInstance extends AutoGenerated.OciInstance {}

export interface OciAgentConfig extends AutoGenerated.OciAgentConfig {}

export interface OciPluginsConfig extends AutoGenerated.OciPluginsConfig {}

export interface OciCreateVnicDetails extends AutoGenerated.OciCreateVnicDetails {}

export interface OciShapeConfig extends AutoGenerated.OciShapeConfig {}

export interface OciSourceDetails extends AutoGenerated.OciSourceDetails {}

export namespace OciInstance {
    export function newResource(type?: string): OciInstance {
        return {
            ...AutoGenerated.OciInstance.newResource('instance'),
        }
    }
    export function cloneResource(resource: OciInstance, type?: string): OciInstance {
        return {
            ...AutoGenerated.OciInstance.cloneResource(resource, 'instance'),
        }
    }
    
    export function newOciAgentConfig(): OciAgentConfig {
        return {
            ...AutoGenerated.OciInstance.newOciAgentConfig(),
        }
    }

    export function newOciPluginsConfig(): OciPluginsConfig {
        return {
            ...AutoGenerated.OciInstance.newOciPluginsConfig(),
        }
    }

    export function newOciCreateVnicDetails(): OciCreateVnicDetails {
        return {
            ...AutoGenerated.OciInstance.newOciCreateVnicDetails(),
        }
    }

    export function newOciShapeConfig(): OciShapeConfig {
        return {
            ...AutoGenerated.OciInstance.newOciShapeConfig(),
        }
    }

    export function newOciSourceDetails(): OciSourceDetails {
        return {
            ...AutoGenerated.OciInstance.newOciSourceDetails(),
        }
    }

}

export class OciInstanceClient {
    static new(): OciInstance {
        return OciInstance.newResource()
    }
    static clone(resource: OciInstance): OciInstance {
        return OciInstance.cloneResource(resource)
    }
}

export default OciInstanceClient
