/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciServiceGateway"

export interface OciServiceGateway extends AutoGenerated.OciServiceGateway {}

export interface OciServices extends AutoGenerated.OciServices {}

export namespace OciServiceGateway {
    export function newResource(type?: string): OciServiceGateway {
        return {
            ...AutoGenerated.OciServiceGateway.newResource('service_gateway'),
        }
    }
    export function cloneResource(resource: OciServiceGateway, type?: string): OciServiceGateway {
        return AutoGenerated.OciServiceGateway.cloneResource(resource, 'service_gateway') as OciServiceGateway
    }
    
    export function newOciServices(): OciServices {
        return {
            ...AutoGenerated.OciServiceGateway.newOciServices(),
        }
    }

}

export class OciServiceGatewayClient {
    static new(): OciServiceGateway {
        return OciServiceGateway.newResource()
    }
    static clone(resource: OciServiceGateway): OciServiceGateway {
        return OciServiceGateway.cloneResource(resource)
    }
}

export default OciServiceGatewayClient
