/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/
// TODO: Remove Following
// @ts-nocheck

import fs from 'fs'
import path from 'path'
import { OcdCodeGenerator } from './OcdCodeGenerator.js'

export class OcdTabularGenerator extends OcdCodeGenerator {
    constructor (prefix: string='Oci') {
        super(prefix)
        this.ignoreAttributes = [...this.commonElements, ...this.commonIgnoreElements]
    }

    writeGeneratedResourceFiles(outputDirectory: string, resource: string, force = false) {return}
    /*
    ** Content for the top level file. This will only be created if it does not exists.
    */
    content = (resource, schema) => {
        const contents = `${this.copyright()}

import { ${this.prefix}TabularResourceProps } from "../../../../../types/ReactComponentProperties.js"
import { OcdTabularContents } from "../${this.prefix}TabularContents.js"

export const ${this.reactResourceName(resource)} = ({ ocdDocument, ${this.prefix.toLowerCase()}Resources, selected }: ${this.prefix}TabularResourceProps): JSX.Element => {
    const columnTitles: string[] = []
    const resourceElements: string[] = []
    return (
        <OcdTabularContents 
            ocdDocument={ocdDocument}
            ${this.prefix.toLowerCase()}Resources={${this.prefix.toLowerCase()}Resources}
            selected={selected}
            columnTitles={columnTitles}
            resourceElements={resourceElements}
            key={'${this.reactResourceName(resource)}TabularContents'}
        />
    )
}
`

        return contents
    }

    /*
    ** Content for the auto generated file this will be written on each execution.
    */
    autoGeneratedContent = (resource, schema) => {
        const contents = ``

        return contents
    }

    reactResourceName = (resource) => this.resourceName(resource)
    reactResourceGeneratedName = (resource) => this.autoGeneratedResourceName(resource)
    outputFilename = (resource) => `${this.propertiesFilename(resource)}.tsx`
}

export default OcdTabularGenerator
// module.exports = { OcdTabularGenerator }
