/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from './generated/AzureAzapiResource'
import * as Model from '../../../../provider/azure/resources'
import { AzureResources } from '../../../../OcdDesign'
import { OcdResourceValidator, OcdValidationResult, OcdValidatorResource } from '../../../OcdResourceValidator'

export namespace AzureAzapiResource {
    export function validateResource(resource: Model.AzureAzapiResource, resources: AzureResources): OcdValidationResult[] {
        return [...AutoGenerated.AzureAzapiResource.validateResource(resource, resources), ...customValidation(resource, resources)]
    }
    export function isResourceValid(resource: Model.AzureAzapiResource, resources: AzureResources): boolean {
        return (validateResource(resource, resources).filter((v: OcdValidationResult) => !v.valid).length > 0)
    }
    export function hasErrors(resource: Model.AzureAzapiResource, resources: AzureResources): boolean {
        return (validateResource(resource, resources).filter((v: OcdValidationResult) => v.type === 'error').length > 0)
    }
    export function hasWarnings(resource: Model.AzureAzapiResource, resources: AzureResources): boolean {
        return (validateResource(resource, resources).filter((v: OcdValidationResult) => v.type === 'warning').length > 0)
    }
    export function hasInformation(resource: Model.AzureAzapiResource, resources: AzureResources): boolean {
        return (validateResource(resource, resources).filter((v: OcdValidationResult) => v.type === 'information').length > 0)
    }
    function customValidation(resource: Model.AzureAzapiResource, resources: AzureResources): OcdValidationResult[] {
        const results: OcdValidationResult[] = []
        return results
    }
}
