/*
** Copyright (c) 2020, 2023, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

import * as AutoGenerated from "./generated/OciNetworkSecurityGroup"

export interface OciNetworkSecurityGroup extends AutoGenerated.OciNetworkSecurityGroup {}

export namespace OciNetworkSecurityGroup {
    export function newResource(type?: string): OciNetworkSecurityGroup {
        return {
            ...AutoGenerated.OciNetworkSecurityGroup.newResource('network_security_group'),
        }
    }
    export function cloneResource(resource: OciNetworkSecurityGroup, type?: string): OciNetworkSecurityGroup {
        return AutoGenerated.OciNetworkSecurityGroup.cloneResource(resource, 'network_security_group') as OciNetworkSecurityGroup
    }
    export function allowedParentTypes(): string[] {
        console.debug('OciNetworkSecurityGroup: Allowed Parent Types')
        return ['Vcn']
    }
    export function getParentId(resource: OciNetworkSecurityGroup): string {
        console.debug('OciNetworkSecurityGroup: Getting Parent Id to for', resource.displayName, resource.id)
        return resource.vcnId
    }
    export function setParentId(resource: OciNetworkSecurityGroup, parentId: string): OciNetworkSecurityGroup {
        console.debug('OciNetworkSecurityGroup: Setting Parent Id to', parentId, 'for', resource.displayName, resource.id)
        resource.vcnId = parentId
        return resource
    }
    export function getConnectionIds(resource: OciNetworkSecurityGroup): string[] {
        // This List of Ids does not include the Parent Id or Compartment Id
        console.debug('OciNetworkSecurityGroup: Getting Connection Ids to for', resource.displayName, resource.id)
        return []
    }
    
}

export class OciNetworkSecurityGroupClient {
    static new(): OciNetworkSecurityGroup {
        return OciNetworkSecurityGroup.newResource()
    }
    static clone(resource: OciNetworkSecurityGroup): OciNetworkSecurityGroup {
        return OciNetworkSecurityGroup.cloneResource(resource)
    }
}

export default OciNetworkSecurityGroupClient
